"""
Tests for the RoutingView API endpoint.

These tests verify that the routing functionality works with string-based
id_trench values (e.g., 'TR-ABCDEFG') instead of integers.

Note: Trench IDs must be in format TR-XXXXXXX where X is a Base29 character
(ABCDEFGHJKLMNPQRSTUVWXYZ234567) due to database validation trigger.
"""

import pytest
from django.contrib.auth import get_user_model
from django.contrib.gis.geos import LineString
from rest_framework import status
from rest_framework.test import APIClient

from apps.api.models import Trench
from .factories import (
    ProjectFactory,
    FlagFactory,
    SurfaceFactory,
    ConstructionTypeFactory,
)

User = get_user_model()


@pytest.fixture
def api_client():
    """Create API client for testing."""
    return APIClient()


@pytest.fixture
def authenticated_client(api_client, user):
    """Create authenticated API client."""
    api_client.force_authenticate(user=user)
    return api_client


@pytest.fixture
def routing_project(db):
    """Create a project for routing tests."""
    return ProjectFactory()


@pytest.fixture
def routing_flag(db):
    """Create a flag for routing tests."""
    return FlagFactory()


@pytest.fixture
def surface(db):
    """Create a surface for trenches."""
    return SurfaceFactory()


@pytest.fixture
def construction_type(db):
    """Create a construction type for trenches."""
    return ConstructionTypeFactory()


@pytest.fixture
def connected_trenches(db, routing_project, routing_flag, surface, construction_type):
    """
    Create a network of connected trenches for routing tests.

    Layout:
        T1 (0,0)---(100,0) T2 (100,0)---(200,0) T3 (200,0)---(300,0)

    Note: id_trench values are auto-generated by database trigger.
    We retrieve them after creation.
    """
    trench1 = Trench.objects.create(
        project=routing_project,
        flag=routing_flag,
        surface=surface,
        construction_type=construction_type,
        length=100.0,
        geom=LineString((0, 0), (100, 0), srid=25832),
    )
    trench2 = Trench.objects.create(
        project=routing_project,
        flag=routing_flag,
        surface=surface,
        construction_type=construction_type,
        length=100.0,
        geom=LineString((100, 0), (200, 0), srid=25832),
    )
    trench3 = Trench.objects.create(
        project=routing_project,
        flag=routing_flag,
        surface=surface,
        construction_type=construction_type,
        length=100.0,
        geom=LineString((200, 0), (300, 0), srid=25832),
    )
    # Refresh to get the auto-generated id_trench values from database
    trench1.refresh_from_db()
    trench2.refresh_from_db()
    trench3.refresh_from_db()
    return [trench1, trench2, trench3]


@pytest.fixture
def disconnected_trench(db, routing_project, routing_flag, surface, construction_type):
    """Create a trench that is not connected to the main network."""
    trench = Trench.objects.create(
        project=routing_project,
        flag=routing_flag,
        surface=surface,
        construction_type=construction_type,
        length=50.0,
        geom=LineString((1000, 1000), (1050, 1000), srid=25832),
    )
    trench.refresh_from_db()
    return trench


@pytest.mark.django_db
class TestRoutingViewStringIds:
    """Test that RoutingView accepts string-based id_trench values."""

    url = "/api/v1/routing/"

    def test_routing_with_string_trench_ids_succeeds(
        self, authenticated_client, connected_trenches, routing_project
    ):
        """Test routing with string-based id_trench values works correctly."""
        start_trench = connected_trenches[0]
        end_trench = connected_trenches[2]

        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": start_trench.id_trench,
                "end_trench_id": end_trench.id_trench,
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_200_OK
        data = response.json()

        assert data["start_trench_id"] == start_trench.id_trench
        assert data["end_trench_id"] == end_trench.id_trench
        assert "traversed_trench_ids" in data
        assert start_trench.id_trench in data["traversed_trench_ids"]
        assert end_trench.id_trench in data["traversed_trench_ids"]
        assert "path_geometry_wkt" in data
        assert "path_length" in data

    def test_routing_with_alphanumeric_trench_ids(
        self,
        authenticated_client,
        routing_project,
        routing_flag,
        surface,
        construction_type,
    ):
        """Test routing works with auto-generated alphanumeric id_trench values."""
        trench1 = Trench.objects.create(
            project=routing_project,
            flag=routing_flag,
            surface=surface,
            construction_type=construction_type,
            length=100.0,
            geom=LineString((0, 0), (100, 0), srid=25832),
        )
        trench2 = Trench.objects.create(
            project=routing_project,
            flag=routing_flag,
            surface=surface,
            construction_type=construction_type,
            length=100.0,
            geom=LineString((100, 0), (200, 0), srid=25832),
        )
        trench1.refresh_from_db()
        trench2.refresh_from_db()

        # Verify id_trench values are string-based (TR-XXXXXXX format)
        assert trench1.id_trench.startswith("TR-")
        assert trench2.id_trench.startswith("TR-")
        assert len(trench1.id_trench) == 10
        assert len(trench2.id_trench) == 10

        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": trench1.id_trench,
                "end_trench_id": trench2.id_trench,
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_200_OK
        data = response.json()
        assert data["start_trench_id"] == trench1.id_trench
        assert data["end_trench_id"] == trench2.id_trench

    def test_routing_adjacent_trenches(
        self, authenticated_client, connected_trenches, routing_project
    ):
        """Test routing between directly adjacent trenches."""
        start_trench = connected_trenches[0]
        end_trench = connected_trenches[1]

        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": start_trench.id_trench,
                "end_trench_id": end_trench.id_trench,
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_200_OK
        data = response.json()

        assert len(data["traversed_trench_ids"]) == 2
        assert start_trench.id_trench in data["traversed_trench_ids"]
        assert end_trench.id_trench in data["traversed_trench_ids"]


@pytest.mark.django_db
class TestRoutingViewValidation:
    """Test RoutingView input validation."""

    url = "/api/v1/routing/"

    def test_missing_start_trench_id_returns_400(
        self, authenticated_client, routing_project
    ):
        """Test that missing start_trench_id returns 400 error."""
        response = authenticated_client.post(
            self.url,
            {
                "end_trench_id": "TR-ABCDEFG",
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert "error" in response.json()

    def test_missing_end_trench_id_returns_400(
        self, authenticated_client, routing_project
    ):
        """Test that missing end_trench_id returns 400 error."""
        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": "TR-ABCDEFG",
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert "error" in response.json()

    def test_empty_trench_ids_returns_400(self, authenticated_client, routing_project):
        """Test that empty trench IDs return 400 error."""
        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": "",
                "end_trench_id": "",
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )
        assert response.status_code == 400


@pytest.mark.django_db
class TestRoutingViewErrors:
    """Test RoutingView error handling."""

    url = "/api/v1/routing/"

    def test_nonexistent_start_trench_returns_404(
        self, authenticated_client, connected_trenches, routing_project
    ):
        """Test that a non-existent start trench returns 404."""
        end_trench = connected_trenches[0]
        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": "TR-ZZZZZZZ",  # Non-existent but valid format
                "end_trench_id": end_trench.id_trench,
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_404_NOT_FOUND
        assert "error" in response.json()
        assert "not found" in response.json()["error"].lower()

    def test_nonexistent_end_trench_returns_404(
        self, authenticated_client, connected_trenches, routing_project
    ):
        """Test that a non-existent end trench returns 404."""
        start_trench = connected_trenches[0]
        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": start_trench.id_trench,
                "end_trench_id": "TR-ZZZZZZZ",  # Non-existent but valid format
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_404_NOT_FOUND
        assert "error" in response.json()
        assert "not found" in response.json()["error"].lower()

    def test_no_path_between_disconnected_trenches_returns_400(
        self,
        authenticated_client,
        connected_trenches,
        disconnected_trench,
        routing_project,
    ):
        """Test that routing between disconnected trenches returns appropriate error."""
        start_trench = connected_trenches[0]
        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": start_trench.id_trench,
                "end_trench_id": disconnected_trench.id_trench,
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert "error" in response.json()
        assert "no path" in response.json()["error"].lower()

    def test_no_trenches_in_project_returns_400(self, authenticated_client):
        """Test that routing in a project with no trenches returns error."""
        empty_project = ProjectFactory()

        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": "TR-ABCDEFG",
                "end_trench_id": "TR-HIJKLMN",
                "project_id": [empty_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert "error" in response.json()


@pytest.mark.django_db
class TestRoutingViewAuthentication:
    """Test RoutingView authentication requirements."""

    url = "/api/v1/routing/"

    def test_unauthenticated_request_returns_401(self, api_client, routing_project):
        """Test that unauthenticated requests are rejected."""
        response = api_client.post(
            self.url,
            {
                "start_trench_id": "TR-TEST001",
                "end_trench_id": "TR-TEST002",
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_401_UNAUTHORIZED


@pytest.mark.django_db
class TestRoutingViewPathCalculation:
    """Test the actual path calculation in RoutingView."""

    url = "/api/v1/routing/"

    def test_path_includes_all_intermediate_trenches(
        self, authenticated_client, connected_trenches, routing_project
    ):
        """Test that the path includes all intermediate trenches."""
        start_trench = connected_trenches[0]
        middle_trench = connected_trenches[1]
        end_trench = connected_trenches[2]

        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": start_trench.id_trench,
                "end_trench_id": end_trench.id_trench,
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_200_OK
        data = response.json()

        traversed_ids = data["traversed_trench_ids"]
        assert len(traversed_ids) == 3
        assert traversed_ids[0] == start_trench.id_trench
        assert traversed_ids[1] == middle_trench.id_trench
        assert traversed_ids[2] == end_trench.id_trench

    def test_path_length_is_calculated(
        self, authenticated_client, connected_trenches, routing_project
    ):
        """Test that path length is correctly calculated."""
        start_trench = connected_trenches[0]
        end_trench = connected_trenches[2]

        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": start_trench.id_trench,
                "end_trench_id": end_trench.id_trench,
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_200_OK
        data = response.json()

        assert data["path_length"] > 0
        # Total length should be approximately 300 (3 trenches * 100 each)
        assert 290 <= data["path_length"] <= 310

    def test_traversed_trench_uuids_are_returned(
        self, authenticated_client, connected_trenches, routing_project
    ):
        """Test that traversed trench UUIDs are returned."""
        start_trench = connected_trenches[0]
        end_trench = connected_trenches[2]

        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": start_trench.id_trench,
                "end_trench_id": end_trench.id_trench,
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_200_OK
        data = response.json()

        assert "traversed_trench_uuids" in data
        assert len(data["traversed_trench_uuids"]) == 3
        # Verify UUIDs are valid UUID strings
        for uuid_str in data["traversed_trench_uuids"]:
            assert len(uuid_str) == 36  # UUID format: 8-4-4-4-12


@pytest.mark.django_db
class TestRoutingViewTolerance:
    """Test tolerance parameter in RoutingView."""

    url = "/api/v1/routing/"

    def test_routing_with_custom_tolerance(
        self,
        authenticated_client,
        routing_project,
        routing_flag,
        surface,
        construction_type,
    ):
        """Test routing with custom tolerance for snapping."""
        # Create trenches with a small gap that requires tolerance
        trench1 = Trench.objects.create(
            project=routing_project,
            flag=routing_flag,
            surface=surface,
            construction_type=construction_type,
            length=100.0,
            geom=LineString((0, 0), (100, 0), srid=25832),
        )
        trench2 = Trench.objects.create(
            project=routing_project,
            flag=routing_flag,
            surface=surface,
            construction_type=construction_type,
            length=100.0,
            geom=LineString((100.5, 0), (200, 0), srid=25832),  # 0.5m gap
        )
        trench1.refresh_from_db()
        trench2.refresh_from_db()

        # With tolerance of 1, the gap should be bridged
        response = authenticated_client.post(
            self.url,
            {
                "start_trench_id": trench1.id_trench,
                "end_trench_id": trench2.id_trench,
                "project_id": [routing_project.id],
                "tolerance": [1],
            },
            format="json",
        )

        assert response.status_code == status.HTTP_200_OK
