from django.urls import include, path, re_path
from rest_framework.routers import DefaultRouter

from .views import (
    AddressViewSet,
    AreaViewSet,
    AttributesAreaTypeViewSet,
    AttributesCableTypeViewSet,
    AttributesCompanyViewSet,
    AttributesComponentStructureViewSet,
    AttributesComponentTypeViewSet,
    AttributesConduitTypeViewSet,
    AttributesConstructionTypeViewSet,
    AttributesFiberColorViewSet,
    AttributesFiberStatusViewSet,
    AttributesMicroductColorViewSet,
    AttributesMicroductStatusViewSet,
    AttributesNetworkLevelViewSet,
    AttributesNodeTypeViewSet,
    AttributesResidentialUnitStatusViewSet,
    AttributesResidentialUnitTypeViewSet,
    AttributesStatusDevelopmentViewSet,
    AttributesStatusViewSet,
    AttributesSurfaceViewSet,
    CableLabelViewSet,
    CableMicropipeConnectionsView,
    CableTypeColorMappingViewSet,
    CableViewSet,
    ConduitImportTemplateView,
    ConduitImportView,
    ConduitsByTrenchesView,
    ConduitViewSet,
    ContainerTypeViewSet,
    ContainerViewSet,
    ContentTypeViewSet,
    DashboardStatisticsView,
    FeatureFilesViewSet,
    FiberSpliceViewSet,
    FiberTraceView,
    FiberViewSet,
    FlagsViewSet,
    FrontendLogView,
    GeoPackageSchemaView,
    get_cable_micropipe_summary,
    get_conduits_for_cable,
    get_trenches_for_cable_connections,
    LayerExtentView,
    LogEntryViewSet,
    MicroductCableConnectionViewSet,
    MicroductConnectionViewSet,
    MicroductViewSet,
    MicropipesByConduitsView,
    NodeCanvasCoordinatesView,
    NodeSlotClipNumberViewSet,
    NodeSlotConfigurationViewSet,
    NodeSlotDividerViewSet,
    NodeStructureViewSet,
    NodeTrenchSelectionViewSet,
    NodeViewSet,
    OlAddressTileViewSet,
    OlAreaTileViewSet,
    OlNodeTileViewSet,
    OlTrenchTileViewSet,
    ProjectsViewSet,
    QGISAuthView,
    ResidentialUnitViewSet,
    RoutingView,
    TrenchConduitCanvasViewSet,
    TrenchConduitConnectionViewSet,
    TrenchesNearNodeView,
    TrenchViewSet,
    WebDAVAuthView,
    WFS3ProxyView,
    WMSLayerViewSet,
    WMSProxyView,
    WMSSourceViewSet,
)

router = DefaultRouter()
router.register(
    r"attributes_cable_type",
    AttributesCableTypeViewSet,
    basename="attributes_cable_type",
)
router.register(
    r"attributes_company",
    AttributesCompanyViewSet,
    basename="attributes_company",
)
router.register(
    r"attributes_conduit_type",
    AttributesConduitTypeViewSet,
    basename="attributes_conduit_type",
)
router.register(
    r"attributes_construction_type",
    AttributesConstructionTypeViewSet,
    basename="attributes_construction_type",
)
router.register(
    r"attributes_surface",
    AttributesSurfaceViewSet,
    basename="attributes_surface",
)
router.register(
    r"attributes_fiber_color",
    AttributesFiberColorViewSet,
    basename="attributes_fiber_color",
)
router.register(
    r"attributes_microduct_color",
    AttributesMicroductColorViewSet,
    basename="attributes_microduct_color",
)
router.register(
    r"attributes_microduct_status",
    AttributesMicroductStatusViewSet,
    basename="attributes_microduct_status",
)
router.register(
    r"attributes_fiber_status",
    AttributesFiberStatusViewSet,
    basename="attributes_fiber_status",
)
router.register(
    r"attributes_network_level",
    AttributesNetworkLevelViewSet,
    basename="attributes_network_level",
)
router.register(
    r"attributes_node_type",
    AttributesNodeTypeViewSet,
    basename="attributes_node_type",
)
router.register(
    r"attributes_status",
    AttributesStatusViewSet,
    basename="attributes_status",
)
router.register(
    r"attributes_area_type",
    AttributesAreaTypeViewSet,
    basename="attributes_area_type",
)
router.register(
    r"attributes_component_type",
    AttributesComponentTypeViewSet,
    basename="attributes_component_type",
)
router.register(
    r"attributes_component_structure",
    AttributesComponentStructureViewSet,
    basename="attributes_component_structure",
)
router.register(
    r"attributes_status_development",
    AttributesStatusDevelopmentViewSet,
    basename="attributes_status_development",
)
router.register(
    r"attributes_residential_unit_type",
    AttributesResidentialUnitTypeViewSet,
    basename="attributes_residential_unit_type",
)
router.register(
    r"attributes_residential_unit_status",
    AttributesResidentialUnitStatusViewSet,
    basename="attributes_residential_unit_status",
)
router.register(r"content-types", ContentTypeViewSet, basename="content-types")
router.register(r"address", AddressViewSet, basename="address")
router.register(r"residential-unit", ResidentialUnitViewSet, basename="residential-unit")
router.register(r"area", AreaViewSet, basename="area")
router.register(r"cable", CableViewSet, basename="cable")
router.register(r"cable_label", CableLabelViewSet, basename="cable_label")
router.register(
    r"cable_type_color_mapping",
    CableTypeColorMappingViewSet,
    basename="cable_type_color_mapping",
)
router.register(r"conduit", ConduitViewSet, basename="conduit")
router.register(r"flags", FlagsViewSet, basename="flags")
router.register(r"feature-files", FeatureFilesViewSet, basename="feature-files")
router.register(r"microduct", MicroductViewSet, basename="microduct")
router.register(
    r"microduct_cable_connection",
    MicroductCableConnectionViewSet,
    basename="microduct_cable_connection",
)
router.register(
    r"microduct_connection", MicroductConnectionViewSet, basename="microduct_connection"
)
router.register(r"fiber", FiberViewSet, basename="fiber")
router.register(r"fiber-splice", FiberSpliceViewSet, basename="fiber-splice")
router.register(r"node", NodeViewSet, basename="node")
router.register(r"projects", ProjectsViewSet, basename="projects")
router.register(r"trench", TrenchViewSet, basename="trench")
router.register(
    r"trench_conduit_connection",
    TrenchConduitConnectionViewSet,
    basename="trench_conduit_connection",
)
router.register(
    r"trench-conduit-canvas",
    TrenchConduitCanvasViewSet,
    basename="trench-conduit-canvas",
)
router.register(r"logs", LogEntryViewSet, basename="logs")
router.register(
    r"node-trench-selection",
    NodeTrenchSelectionViewSet,
    basename="node-trench-selection",
)
router.register(
    r"node-structure",
    NodeStructureViewSet,
    basename="node-structure",
)
router.register(
    r"node-slot-configuration",
    NodeSlotConfigurationViewSet,
    basename="node-slot-configuration",
)
router.register(
    r"node-slot-divider",
    NodeSlotDividerViewSet,
    basename="node-slot-divider",
)
router.register(
    r"node-slot-clip-number",
    NodeSlotClipNumberViewSet,
    basename="node-slot-clip-number",
)
router.register(
    r"container-type",
    ContainerTypeViewSet,
    basename="container-type",
)
router.register(
    r"container",
    ContainerViewSet,
    basename="container",
)
router.register(r"wms-sources", WMSSourceViewSet, basename="wms-sources")
router.register(r"wms-layers", WMSLayerViewSet, basename="wms-layers")

urlpatterns = [
    path("logs/frontend/", FrontendLogView.as_view(), name="frontend-logs"),
    path("", include(router.urls)),
    path(
        "template/conduit/",
        ConduitImportTemplateView.as_view(),
        name="conduit-import-template",
    ),
    path("import/conduit/", ConduitImportView.as_view(), name="conduit-import"),
    path("schema.gpkg", GeoPackageSchemaView.as_view(), name="geopackage-schema"),
    path(
        "ol_address_tiles/<int:z>/<int:x>/<int:y>.mvt",
        OlAddressTileViewSet.as_view(),
        name="ol_address_tiles",
    ),
    path(
        "ol_node_tiles/<int:z>/<int:x>/<int:y>.mvt",
        OlNodeTileViewSet.as_view(),
        name="ol_node_tiles",
    ),
    path(
        "ol_trench_tiles/<int:z>/<int:x>/<int:y>.mvt",
        OlTrenchTileViewSet.as_view(),
        name="ol_trench_tiles",
    ),
    path(
        "ol_area_tiles/<int:z>/<int:x>/<int:y>.mvt",
        OlAreaTileViewSet.as_view(),
        name="ol_area_tiles",
    ),
    path(
        "routing/",
        RoutingView.as_view(),
        name="routing",
    ),
    path(
        "trenches-near-node/",
        TrenchesNearNodeView.as_view(),
        name="trenches-near-node",
    ),
    path(
        "canvas-coordinates/",
        NodeCanvasCoordinatesView.as_view(),
        name="node-canvas-coordinates",
    ),
    path(
        "auth/webdav-auth/",
        WebDAVAuthView.as_view(),
        name="webdav-auth",
    ),
    path(
        "auth/qgis-auth/",
        QGISAuthView.as_view(),
        name="qgis-auth",
    ),
    path(
        "layer-extent/",
        LayerExtentView.as_view(),
        name="layer-extent",
    ),
    path(
        "conduits/by-trenches/",
        ConduitsByTrenchesView.as_view(),
        name="conduits-by-trenches",
    ),
    path(
        "micropipes/by-conduits/",
        MicropipesByConduitsView.as_view(),
        name="micropipes-by-conduits",
    ),
    path(
        "cables/<uuid:cable_id>/micropipe-connections/",
        CableMicropipeConnectionsView.as_view(),
        name="cable-micropipe-connections",
    ),
    path(
        "cables/<uuid:cable_id>/linked-trenches/",
        get_trenches_for_cable_connections,
        name="cable-linked-trenches",
    ),
    path(
        "cables/<uuid:cable_id>/conduits/",
        get_conduits_for_cable,
        name="cable-conduits",
    ),
    path(
        "cables/micropipe-summary/<int:project_id>/",
        get_cable_micropipe_summary,
        name="cable-micropipe-summary",
    ),
    path(
        "wms-proxy/<uuid:source_id>/",
        WMSProxyView.as_view(),
        name="wms-proxy",
    ),
    re_path(
        r"^wfs3/(?P<project_name>[\w-]+)/(?P<wfs3_path>.*)$",
        WFS3ProxyView.as_view(),
        name="wfs3-proxy",
    ),
    re_path(
        r"^wfs3/(?P<project_name>[\w-]+)/?$",
        WFS3ProxyView.as_view(),
        name="wfs3-proxy-root",
    ),
    path(
        "dashboard/statistics/",
        DashboardStatisticsView.as_view(),
        name="dashboard-statistics",
    ),
    path(
        "fiber-trace/",
        FiberTraceView.as_view(),
        name="fiber-trace",
    ),
]
