# Generated by Django 4.2.17 on 2025-06-26 04:06

import apps.api.models
import apps.api.storage
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlTrench',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('id_trench', models.IntegerField(verbose_name='Trench ID')),
                ('construction_depth', models.IntegerField(null=True, verbose_name='Construction Depth')),
                ('construction_details', models.TextField(null=True, verbose_name='Construction Details')),
                ('internal_execution', models.BooleanField(null=True, verbose_name='Internal Execution')),
                ('funding_status', models.BooleanField(null=True, verbose_name='Funding Status')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('house_connection', models.BooleanField(null=True, verbose_name='House Connection')),
                ('length', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Length')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=25832, verbose_name='Geometry')),
            ],
            options={
                'verbose_name': 'OL Trench',
                'verbose_name_plural': 'OL Trenches',
                'db_table': 'ol_trench',
                'ordering': ['id_trench'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributesCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.TextField(verbose_name='Company')),
                ('city', models.TextField(null=True, verbose_name='City')),
                ('postal_code', models.TextField(null=True, verbose_name='Postal Code')),
                ('street', models.TextField(null=True, verbose_name='Street')),
                ('housenumber', models.TextField(null=True, verbose_name='Housenumber')),
                ('phone', models.TextField(null=True, verbose_name='Phone')),
                ('email', models.TextField(null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'attributes_company',
            },
        ),
        migrations.CreateModel(
            name='AttributesConduitType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('conduit_type', models.TextField(verbose_name='Conduit Type')),
                ('conduit_count', models.IntegerField(verbose_name='Conduit Count')),
                ('color_code', models.JSONField(verbose_name='Color Code')),
                ('conduit_type_alias', models.TextField(null=True, verbose_name='Conduit Type Alias')),
                ('conduit_type_microduct', models.IntegerField(null=True, verbose_name='Conduit Type Microduct')),
            ],
            options={
                'verbose_name': 'Conduit Type',
                'verbose_name_plural': 'Conduit Types',
                'db_table': 'attributes_conduit_type',
            },
        ),
        migrations.CreateModel(
            name='AttributesConstructionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('construction_type', models.TextField(verbose_name='Construction Type')),
            ],
            options={
                'verbose_name': 'Construction Type',
                'verbose_name_plural': 'Construction Types',
                'db_table': 'attributes_construction_type',
            },
        ),
        migrations.CreateModel(
            name='AttributesNetworkLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('network_level', models.TextField(verbose_name='Network Level')),
            ],
            options={
                'verbose_name': 'Network Level',
                'verbose_name_plural': 'Network Levels',
                'db_table': 'attributes_network_level',
            },
        ),
        migrations.CreateModel(
            name='AttributesNodeType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('node_type', models.TextField(verbose_name='Node Type')),
                ('dimension', models.TextField(null=True, verbose_name='Dimension')),
                ('group', models.TextField(null=True, verbose_name='Group')),
                ('company', models.TextField(null=True, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Node Type',
                'verbose_name_plural': 'Node Types',
                'db_table': 'attributes_node_type',
            },
        ),
        migrations.CreateModel(
            name='AttributesPhase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phase', models.TextField(verbose_name='Phase')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'db_table': 'attributes_phase',
            },
        ),
        migrations.CreateModel(
            name='AttributesStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField(unique=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'db_table': 'attributes_status',
            },
        ),
        migrations.CreateModel(
            name='AttributesSurface',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surface', models.TextField(verbose_name='Surface')),
                ('sealing', models.BooleanField(verbose_name='Sealing')),
            ],
            options={
                'verbose_name': 'Surface',
                'verbose_name_plural': 'Surfaces',
                'db_table': 'attributes_surface',
            },
        ),
        migrations.CreateModel(
            name='Conduit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, verbose_name='Conduit Name')),
                ('outer_conduit', models.TextField(null=True)),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('conduit_type', models.ForeignKey(db_column='conduit_type', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.attributesconduittype', verbose_name='Conduit Type')),
                ('constructor', models.ForeignKey(db_column='constructor', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructed_conduits', to='api.attributescompany', verbose_name='Constructor')),
            ],
            options={
                'verbose_name': 'Conduit',
                'verbose_name_plural': 'Conduits',
                'db_table': 'conduit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileTypeCategory',
            fields=[
                ('extension', models.CharField(help_text="File extension without the dot (e.g., 'pdf', 'jpg')", max_length=10, primary_key=True, serialize=False, verbose_name='File Extension')),
                ('category', models.CharField(help_text="Category used for folder organization (e.g., 'photos', 'documents')", max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, help_text='Optional description of this file type', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'File Type Category',
                'verbose_name_plural': 'File Type Categories',
                'db_table': 'file_type_category',
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('flag', models.TextField(unique=True, verbose_name='Flag')),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
                'db_table': 'flags',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project', models.TextField(unique=True, verbose_name='Project')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='StoragePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('AUTO', 'Automatic Organization'), ('MANUAL', 'User Defined')], default='AUTO', max_length=10)),
                ('folder_structure', models.JSONField(default=dict, help_text="Custom folder structure for different feature types. Example: {'trench': 'trenches', 'node': 'nodes'}")),
            ],
            options={
                'verbose_name': 'Storage Preference',
                'verbose_name_plural': 'Storage Preferences',
                'db_table': 'storage_preferences',
            },
        ),
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_trench', models.IntegerField(unique=True, verbose_name='Trench ID')),
                ('construction_depth', models.IntegerField(null=True, verbose_name='Construction Depth')),
                ('construction_details', models.TextField(null=True, verbose_name='Construction Details')),
                ('internal_execution', models.BooleanField(null=True, verbose_name='Internal Execution')),
                ('funding_status', models.BooleanField(null=True, verbose_name='Funding Status')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('house_connection', models.BooleanField(default=False, null=True, verbose_name='House Connection')),
                ('length', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Length')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(spatial_index=False, srid=25832, verbose_name='Geometry')),
                ('construction_type', models.ForeignKey(db_column='construction_type', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.attributesconstructiontype', verbose_name='Construction Type')),
                ('constructor', models.ForeignKey(db_column='constructor', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_trenches', to='api.attributescompany', verbose_name='Constructor')),
                ('flag', models.ForeignKey(db_column='flag', db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.flags', verbose_name='Flag')),
                ('owner', models.ForeignKey(db_column='owner', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_trenches', to='api.attributescompany', verbose_name='Owner')),
                ('phase', models.ForeignKey(db_column='phase', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributesphase', verbose_name='Phase')),
                ('project', models.ForeignKey(db_column='project', db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.projects', verbose_name='Project')),
                ('status', models.ForeignKey(db_column='status', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributesstatus', verbose_name='Status')),
                ('surface', models.ForeignKey(db_column='surface', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.attributessurface', verbose_name='Surface')),
            ],
            options={
                'verbose_name': 'Trench',
                'verbose_name_plural': 'Trenches',
                'db_table': 'trench',
                'ordering': ['id_trench'],
            },
        ),
        migrations.CreateModel(
            name='TrenchConduitConnection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uuid_conduit', models.ForeignKey(db_column='uuid_conduit', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.conduit', verbose_name='Conduit')),
                ('uuid_trench', models.ForeignKey(db_column='uuid_trench', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.trench', verbose_name='Trench')),
            ],
            options={
                'verbose_name': 'Trench Conduit Connection',
                'verbose_name_plural': 'Trench Conduit Connections',
                'db_table': 'trench_conduit_connect',
            },
        ),
        migrations.CreateModel(
            name='FeatureFiles',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(verbose_name='Feature ID')),
                ('file_path', models.FileField(storage=apps.api.storage.NextcloudStorage(), upload_to=apps.api.models.FeatureFiles.get_upload_path, verbose_name='File Path')),
                ('file_name', models.TextField(verbose_name='File Name')),
                ('file_type', models.TextField(null=True, verbose_name='File Type')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label': 'api', 'model__in': ['trench', 'node', 'address', 'residentialunit']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Feature Type')),
            ],
            options={
                'verbose_name': 'Feature File',
                'verbose_name_plural': 'Feature Files',
                'db_table': 'feature_files',
            },
        ),
        migrations.AddField(
            model_name='conduit',
            name='flag',
            field=models.ForeignKey(db_column='flag', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.flags', verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='manufacturer',
            field=models.ForeignKey(db_column='manufacturer', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manufactured_conduits', to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='network_level',
            field=models.ForeignKey(db_column='network_level', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesnetworklevel', verbose_name='Network Level'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='owner',
            field=models.ForeignKey(db_column='owner', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_conduits', to='api.attributescompany', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='project',
            field=models.ForeignKey(db_column='project', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.projects', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='status',
            field=models.ForeignKey(db_column='status', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesstatus', verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='attributessurface',
            index=models.Index(fields=['surface'], name='idx_surface_surface'),
        ),
        migrations.AddIndex(
            model_name='attributesstatus',
            index=models.Index(fields=['status'], name='idx_status_status'),
        ),
        migrations.AddIndex(
            model_name='attributesphase',
            index=models.Index(fields=['phase'], name='idx_phase_phase'),
        ),
        migrations.AddIndex(
            model_name='attributesnodetype',
            index=models.Index(fields=['node_type'], name='idx_node_type_node_type'),
        ),
        migrations.AddIndex(
            model_name='attributesnetworklevel',
            index=models.Index(fields=['network_level'], name='idx_network_level_net_level'),
        ),
        migrations.AddIndex(
            model_name='attributesconstructiontype',
            index=models.Index(fields=['construction_type'], name='idx_construction_type'),
        ),
        migrations.AddField(
            model_name='attributesconduittype',
            name='manufacturer',
            field=models.ForeignKey(db_column='manufacturer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AddIndex(
            model_name='attributescompany',
            index=models.Index(fields=['company'], name='idx_company_company'),
        ),
        migrations.AddIndex(
            model_name='trenchconduitconnection',
            index=models.Index(fields=['uuid_trench'], name='idx_trench_conduit_con_trench'),
        ),
        migrations.AddIndex(
            model_name='trenchconduitconnection',
            index=models.Index(fields=['uuid_conduit'], name='idx_trench_conduit_con_cond'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['id_trench'], name='idx_trench_id_trench'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['surface'], name='idx_trench_surface'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['construction_type'], name='idx_trench_construction_type'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['status'], name='idx_trench_status'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['phase'], name='idx_trench_phase'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['owner'], name='idx_trench_owner'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['constructor'], name='idx_trench_constructor'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['geom'], name='idx_trench_geom'),
        ),
        migrations.AddIndex(
            model_name='featurefiles',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_feature_files_type_id'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['name'], name='idx_conduit_name'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['conduit_type'], name='idx_conduit_conduit_type'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['status'], name='idx_conduit_status'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['network_level'], name='idx_conduit_network_level'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['owner'], name='idx_conduit_owner'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['constructor'], name='idx_conduit_constructor'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['manufacturer'], name='idx_conduit_manufacturer'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['project'], name='idx_conduit_project'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['flag'], name='idx_conduit_flag'),
        ),
        migrations.AddIndex(
            model_name='attributesconduittype',
            index=models.Index(fields=['conduit_type'], name='idx_conduit_type_conduit_type'),
        ),
    ]
