# Generated by Django 4.2.17 on 2025-01-30 20:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesConstructionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('construction_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AttributesSurface',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surface', models.TextField()),
                ('sealing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_trench', models.IntegerField()),
                ('construction_depth', models.IntegerField(null=True)),
                ('construction_details', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('phase', models.TextField(null=True)),
                ('internal_execution', models.BooleanField(null=True)),
                ('funding_status', models.BooleanField(null=True)),
                ('owner', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('comment', models.TextField(null=True)),
                ('house_connection', models.BooleanField(default=False, null=True)),
                ('length', models.DecimalField(decimal_places=4, max_digits=8)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=25832)),
                ('construction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributesconstructiontype')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributessurface')),
            ],
        ),
    ]
