# Generated by Django 4.2.17 on 2025-01-30 21:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.TextField()),
                ('city', models.TextField(null=True)),
                ('postal_code', models.TextField(null=True)),
                ('street', models.TextField(null=True)),
                ('housenumber', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
            ],
            options={
                'db_table': 'attributes_company',
            },
        ),
        migrations.CreateModel(
            name='AttributesConstructionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('construction_type', models.TextField()),
            ],
            options={
                'db_table': 'attributes_construction_type',
            },
        ),
        migrations.CreateModel(
            name='AttributesNodeType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('node_type', models.TextField()),
                ('dimension', models.TextField(null=True)),
                ('group', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
            ],
            options={
                'db_table': 'attributes_node_type',
            },
        ),
        migrations.CreateModel(
            name='AttributesPhase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phase', models.TextField()),
            ],
            options={
                'db_table': 'attributes_phase',
            },
        ),
        migrations.CreateModel(
            name='AttributesStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'attributes_status',
            },
        ),
        migrations.CreateModel(
            name='AttributesSurface',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surface', models.TextField()),
                ('sealing', models.BooleanField()),
            ],
            options={
                'db_table': 'attributes_surface',
            },
        ),
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('dd5cd888-88a5-4f76-968d-998cb580b545'), primary_key=True, serialize=False)),
                ('id_trench', models.IntegerField()),
                ('construction_depth', models.IntegerField(null=True)),
                ('construction_details', models.TextField(null=True)),
                ('internal_execution', models.BooleanField(null=True)),
                ('funding_status', models.BooleanField(null=True)),
                ('date', models.DateField(null=True)),
                ('comment', models.TextField(null=True)),
                ('house_connection', models.BooleanField(default=False, null=True)),
                ('length', models.DecimalField(decimal_places=4, max_digits=8)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(spatial_index=False, srid=25832)),
                ('company', models.ForeignKey(db_column='company', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_trenches', to='api.attributescompany')),
                ('construction_type', models.ForeignKey(db_column='construction_type', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.attributesconstructiontype')),
                ('owner', models.ForeignKey(db_column='owner', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_trenches', to='api.attributescompany')),
                ('phase', models.ForeignKey(db_column='phase', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributesphase')),
                ('status', models.ForeignKey(db_column='status', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributesstatus')),
                ('surface', models.ForeignKey(db_column='surface', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.attributessurface')),
            ],
            options={
                'db_table': 'trench',
            },
        ),
        migrations.AddIndex(
            model_name='attributessurface',
            index=models.Index(fields=['surface'], name='idx_surface_surface'),
        ),
        migrations.AddIndex(
            model_name='attributesstatus',
            index=models.Index(fields=['status'], name='idx_status_status'),
        ),
        migrations.AddIndex(
            model_name='attributesphase',
            index=models.Index(fields=['phase'], name='idx_phase_phase'),
        ),
        migrations.AddIndex(
            model_name='attributesnodetype',
            index=models.Index(fields=['node_type'], name='idx_node_type_node_type'),
        ),
        migrations.AddIndex(
            model_name='attributesconstructiontype',
            index=models.Index(fields=['construction_type'], name='idx_construction_type'),
        ),
        migrations.AddIndex(
            model_name='attributescompany',
            index=models.Index(fields=['company'], name='idx_company_company'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['id_trench'], name='idx_trench_id_trench'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['surface'], name='idx_trench_surface'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['construction_type'], name='idx_trench_construction_type'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['status'], name='idx_trench_status'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['phase'], name='idx_trench_phase'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['owner'], name='idx_trench_owner'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['company'], name='idx_trench_company'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['geom'], name='idx_trench_geom'),
        ),
    ]
