# Generated by Django 4.2.17 on 2025-01-31 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            create or replace function fn_notify_qgis() returns trigger
            language plpgsql
                as
            $$
            begin
                begin notify qgis;
                return null;
                end;
            end;
            $$;
            """
        ),
        migrations.RunSQL(
            """
            create or replace function fn_validate_linestring_geom() returns trigger
            language plpgsql
                as
            $$
            begin
                if not st_isvalid(new.geom) then
                    raise exception 'Invalid geometry: %', st_isvalidreason(new.geom);
                elseif not st_issimple(new.geom) then
                    raise exception 'Geometry is not simple';
                else
                    return new;
                end if;
            end;
            $$;
            """
        ),
        migrations.RunSQL(
            """
            create or replace function public.fn_calculate_length_from_geom() returns trigger
                language plpgsql
                    as
                $$
                begin
                    new.length := st_length(new.geom);
                    return new;
                end;
                $$;
            """
        ),
        migrations.RunSQL(
            """
            create or replace function fn_set_id_trench() returns trigger
                language plpgsql
            as
            $$
            begin
                new.id_trench := fn_id_generator(new.id_trench);
                return new;
            end;
            $$;
            """
        ),
        migrations.RunSQL(
            """
            create or replace function fn_id_generator(object_id integer) returns integer
                language plpgsql
            as
            $$
                declare
                    new_object_id int;
            begin
                new_object_id := coalesce(max(object_id), 0) + 1;
                return new_object_id;
            end;
            $$;
            """
        ),
    ]
