# Generated by Django 4.2.17 on 2025-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'attributes_status',
            },
        ),
        migrations.AlterModelTable(
            name='attributesconstructiontype',
            table='attributes_construction_type',
        ),
        migrations.AlterModelTable(
            name='attributessurface',
            table='attributes_surface',
        ),
        migrations.AlterModelTable(
            name='trench',
            table='trench',
        ),
    ]
