# Generated by Django 4.2.17 on 2025-01-31 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            create or replace function fn_notify_qgis() returns trigger
            language plpgsql
                as
            $$
            begin
                begin notify qgis;
                return null;
                end;
            end;
            $$;
            """
        ),
        migrations.RunSQL(
            """
            create or replace function fn_validate_linestring_geom() returns trigger
            language plpgsql
                as
            $$
            begin
                if not st_isvalid(new.geom) then
                    raise exception 'Invalid geometry: %', st_isvalidreason(new.geom);
                elseif not st_issimple(new.geom) then
                    raise exception 'Geometry is not simple';
                else
                    return new;
                end if;
            end;
            $$;
            """
        ),
        migrations.RunSQL(
            """
            create or replace function public.fn_calculate_length_from_geom() returns trigger
                language plpgsql
                    as
                $$
                begin
                    new.length := st_length(new.geom);
                    return new;
                end;
                $$;
            """
        ),
        migrations.RunSQL(
            """
            create or replace function fn_generate_id_trench()
                returns trigger
                language plpgsql
                as
            $$
            declare
                next_id  bigint;
                lock_key bigint := 123456789;
            begin
                if tg_op = 'update' and new.id_trench is not null then
                    return old;
                end if;

                PERFORM pg_advisory_xact_lock(lock_key);

                select coalesce(max(id_trench), 0) + 1
                into next_id
                from trench;

                new.id_trench := next_id;
                return new;
            end;
            $$;
            """
        ),
    ]
