# Generated by Django 4.2.17 on 2025-01-31 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_routines"),
    ]

    operations = [
        migrations.RunSQL(
            """
            alter table trench alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_01_validate_linestring_geom
                before insert or update of geom
                on trench
                for each row
                execute procedure fn_validate_linestring_geom();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_02_calculate_length_from_geom
                before insert or update of geom
                on trench
                for each row
                execute procedure fn_calculate_length_from_geom();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_03_notify_qgis
                after insert or update or delete
                on trench
                for each statement
            execute procedure fn_notify_qgis();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_04_set_id_trench
                before insert
                on trench
                for each row
            execute procedure fn_set_id_trench();
            """
        ),
    ]
