# Generated by Django 4.2.17 on 2025-01-31 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_routines"),
    ]

    operations = [
        migrations.RunSQL(
            """
            alter table trench alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            alter table trench alter column id_trench add generated always as identity;
            """
        ),
        migrations.RunSQL(
            """
            alter table feature_files alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            alter table trench_conduit_connect alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            alter table node alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            alter table address alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            create unique index unique_address on address (zip_code,street,housenumber,coalesce(house_number_suffix,''));
            """
        ),
        migrations.RunSQL(
            """
            alter table microduct alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            alter table microduct_connection alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            alter table cable alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            alter table microduct_cable_connection alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            alter table cable_label alter column uuid set default gen_random_uuid();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_01_validate_linestring_geom
                before insert or update of geom
                on trench
                for each row
                execute procedure fn_validate_linestring_geom();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_02_calculate_length_from_geom
                before insert or update of geom
                on trench
                for each row
                execute procedure fn_calculate_length_from_geom();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_03_notify_qgis
                after insert or update or delete
                on trench
                for each statement
            execute procedure fn_notify_qgis();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_04_generate_id_trench
                before insert or update of id_trench
                on trench
                for each row
            execute procedure fn_generate_id_trench();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_05_delete_microduct_connection
                before update of geom
                on trench
                for each row
            execute procedure fn_delete_microduct_connection_on_geom_change();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_01_delete_microduct_connection
                before update of geom
                on node
                for each row
            execute procedure fn_delete_microduct_connection_on_geom_change();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_02_notify_node_canvas_position
                after update of canvas_x, canvas_y
                on node
                for each row
            execute procedure fn_notify_node_canvas_position();
            """
        ),
        migrations.RunSQL(
            """
            create trigger tg_01_delete_microduct_connection
                after delete
                on trench_conduit_connect
                for each row
            execute procedure fn_delete_microduct_connection_if_conduit_not_in_trench();
            """
        ),
    ]
