# Generated by Django 4.2.17 on 2025-01-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attributesstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.TextField()),
                ('city', models.TextField(null=True)),
                ('postal_code', models.TextField(null=True)),
                ('street', models.TextField(null=True)),
                ('housenumber', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
            ],
            options={
                'db_table': 'attributes_company',
            },
        ),
        migrations.CreateModel(
            name='AttributesNodeType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('node_type', models.TextField(null=True)),
                ('dimension', models.TextField(null=True)),
                ('group', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
            ],
            options={
                'db_table': 'attributes_node_type',
            },
        ),
        migrations.CreateModel(
            name='AttributesPhase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phase', models.TextField()),
            ],
            options={
                'db_table': 'attributes_phase',
            },
        ),
    ]
