# Generated by Django 4.2.17 on 2025-01-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attributescompany_attributesnodetype_attributesphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trench',
            name='company',
            field=models.ForeignKey(db_column='fk_trench_company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_trenches', to='api.attributescompany'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='construction_type',
            field=models.ForeignKey(db_column='fk_trench_construction_type', on_delete=django.db.models.deletion.CASCADE, to='api.attributesconstructiontype'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='owner',
            field=models.ForeignKey(db_column='fk_trench_owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_trenches', to='api.attributescompany'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='phase',
            field=models.ForeignKey(db_column='fk_trench_phase', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributesphase'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='status',
            field=models.ForeignKey(db_column='fk_trench_status', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributesstatus'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='surface',
            field=models.ForeignKey(db_column='fk_trench_surface', on_delete=django.db.models.deletion.CASCADE, to='api.attributessurface'),
        ),
    ]
