# Generated by Django 4.2.17 on 2025-02-07 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_ddl"),
    ]

    operations = [
        migrations.RunSQL("""
    create view public.ol_trench as
        select
            t.uuid,
            t.id_trench,
            t.construction_depth,
            t.construction_details,
            t.internal_execution,
            t.funding_status,
            t.date,
            t.comment,
            t.house_connection,
            t.length,
            st_transform(t.geom, 3857) as geom,
            t.constructor,
            t.construction_type,
            t.owner,
            t.phase,
            t.status,
            t.surface,
            t.project,
            t.flag
        from trench t
        order by t.id_trench;
    """),
        migrations.RunSQL("""
    create view ol_node as
    select 
        n.uuid,
        n.name,
        n.warranty,
        n.date,
        st_transform(n.geom, 3857) AS geom,
        n.constructor,
        n.flag,
        n.manufacturer,
        n.network_level,
        n.node_type,
        n.owner,
        n.project,
        n.status,
        n.uuid_address
    from node n;
    """),
        migrations.RunSQL("""
    create view ol_address as
    select 
        a.uuid,
        a.id_address,
        a.zip_code,
        a.city,
        a.district,
        a.street,
        a.housenumber,
        a.house_number_suffix,
        st_transform(a.geom, 3857) AS geom,
        a.flag,
        a.project,
        a.status_development
    from address a;
    """),
        migrations.RunSQL("""
    create view public.qgis_trench as 
        select 
                id_trench, 
                construction_type, 
                surface, 
                flag, 
                project, 
                geom
        from public.trench;
    """),
    ]
