# Generated by Django 4.2.17 on 2025-02-07 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_trench_ddl"),
    ]

    operations = [
        migrations.RunSQL("""
    create view public.ol_trench as
        select
            t.uuid,
            t.id_trench,
            t.construction_depth,
            t.construction_details,
            t.internal_execution,
            t.funding_status,
            t.date,
            t.comment,
            t.house_connection,
            t.length,
            st_transform(t.geom, 3857) as geom,
            t.company,
            t.construction_type,
            t.owner,
            t.phase,
            t.status,
            t.surface,
            t.project
        from trench t
        order by t.id_trench;
    """),
    ]
