# Generated by Django 4.2.17 on 2025-07-20 04:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesMicroductStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('microduct_status', models.TextField(db_index=True, unique=True, verbose_name='Microduct Status')),
            ],
            options={
                'verbose_name': 'Microduct Status',
                'verbose_name_plural': 'Microduct Statuses',
                'db_table': 'attributes_microduct_status',
            },
        ),
        migrations.AlterField(
            model_name='gtpkmetadata',
            name='pk_column_idx',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gtpkmetadata',
            name='pk_policy',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gtpkmetadata',
            name='pk_sequence',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Microduct',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='Number')),
                ('color', models.TextField(verbose_name='Color')),
                ('microduct_status', models.ForeignKey(db_column='microduct_status', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.attributesmicroductstatus', verbose_name='Microduct Status')),
                ('uuid_conduit', models.ForeignKey(db_column='uuid_conduit', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.conduit', verbose_name='Conduit')),
                ('uuid_node', models.ForeignKey(db_column='uuid_node', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.node', verbose_name='Node')),
            ],
            options={
                'verbose_name': 'Microduct',
                'verbose_name_plural': 'Microducts',
                'db_table': 'microduct',
                'indexes': [models.Index(fields=['uuid_conduit'], name='idx_microduct_conduit'), models.Index(fields=['number'], name='idx_microduct_number'), models.Index(fields=['color'], name='idx_microduct_color'), models.Index(fields=['microduct_status'], name='idx_microduct_status'), models.Index(fields=['uuid_node'], name='idx_microduct_node')],
            },
        ),
    ]
