# Generated by Django 4.2.17 on 2025-09-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='canvas_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Canvas X'),
        ),
        migrations.AddField(
            model_name='node',
            name='canvas_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Canvas Y'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['canvas_x'], name='idx_node_canvas_x'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['canvas_y'], name='idx_node_canvas_y'),
        ),
    ]
