# Generated by Django 4.2.17 on 2025-02-24 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trench_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFiles',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('feature_id', models.UUIDField(verbose_name='Feature ID')),
                ('file_path', models.FileField(upload_to=None, verbose_name='File Path')),
                ('file_name', models.TextField(verbose_name='File Name')),
                ('file_type', models.TextField(verbose_name='File Type')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Feature File',
                'verbose_name_plural': 'Feature Files',
                'db_table': 'feature_files',
            },
        ),
        migrations.AlterModelOptions(
            name='attributescompany',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='attributesconstructiontype',
            options={'verbose_name': 'Construction Type', 'verbose_name_plural': 'Construction Types'},
        ),
        migrations.AlterModelOptions(
            name='attributesphase',
            options={'verbose_name': 'Phase', 'verbose_name_plural': 'Phases'},
        ),
        migrations.AlterModelOptions(
            name='attributesstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='attributessurface',
            options={'verbose_name': 'Surface', 'verbose_name_plural': 'Surfaces'},
        ),
        migrations.DeleteModel(
            name='TrenchFiles',
        ),
        migrations.AddIndex(
            model_name='featurefiles',
            index=models.Index(fields=['feature_id'], name='idx_feature_files_feature_id'),
        ),
    ]
