# Generated by Django 4.2.17 on 2025-06-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trench_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtPkMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_schema', models.CharField(max_length=32)),
                ('table_name', models.CharField(max_length=32)),
                ('pk_column', models.CharField(max_length=32)),
                ('pk_column_idx', models.IntegerField()),
                ('pk_policy', models.CharField(max_length=32)),
                ('pk_sequence', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'GT PK Metadata',
                'verbose_name_plural': 'GT PK Metadata',
                'db_table': 'gt_pk_metadata',
                'indexes': [models.Index(fields=['table_schema', 'table_name', 'pk_column'], name='idx_gpm_schema_name_pk_column')],
            },
        ),
        migrations.AddConstraint(
            model_name='gtpkmetadata',
            constraint=models.UniqueConstraint(fields=('table_schema', 'table_name', 'pk_column'), name='unique_gt_pk_metadata'),
        ),
    ]
