# Generated by Django 4.2.17 on 2025-09-25 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_node_canvas_x_node_canvas_y_node_idx_node_canvas_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_key', models.CharField(help_text="Unique identifier for sync operation (e.g., 'project_1', 'project_1_flag_5')", max_length=100, unique=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('scale', models.FloatField(blank=True, null=True)),
                ('center_x', models.FloatField(blank=True, null=True)),
                ('center_y', models.FloatField(blank=True, null=True)),
                ('nodes_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canvas Sync Status',
                'verbose_name_plural': 'Canvas Sync Statuses',
                'db_table': 'canvas_sync_status',
            },
        ),
    ]
