# Generated by Django 4.2.17 on 2025-07-20 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attributesmicroductstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microduct',
            options={'ordering': ['uuid_conduit', 'number'], 'verbose_name': 'Microduct', 'verbose_name_plural': 'Microducts'},
        ),
        migrations.CreateModel(
            name='MicroductConnection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uuid_microduct_from', models.ForeignKey(db_column='uuid_microduct_from', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='microduct_connections_from', to='api.microduct', verbose_name='Microduct From')),
                ('uuid_microduct_to', models.ForeignKey(db_column='uuid_microduct_to', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='microduct_connections_to', to='api.microduct', verbose_name='Microduct To')),
                ('uuid_node', models.ForeignKey(db_column='uuid_node', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.node', verbose_name='Node')),
            ],
            options={
                'verbose_name': 'Microduct Connection',
                'verbose_name_plural': 'Microduct Connections',
                'db_table': 'microduct_connection',
                'ordering': ['uuid_microduct_from', 'uuid_microduct_to'],
                'indexes': [models.Index(fields=['uuid_microduct_from'], name='idx_microduct_connection_from'), models.Index(fields=['uuid_microduct_to'], name='idx_microduct_connection_to'), models.Index(fields=['uuid_node'], name='idx_microduct_connection_node')],
            },
        ),
    ]
