# Generated by Django 4.2.17 on 2025-02-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("api", "0005_featurefiles_alter_attributescompany_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="featurefiles",
            name="idx_feature_files_feature_id",
        ),
        migrations.RenameField(
            model_name="featurefiles",
            old_name="feature_id",
            new_name="object_id",
        ),
        migrations.AddField(
            model_name="featurefiles",
            name="content_type",
            field=models.ForeignKey(
                default=13,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Feature Type",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="featurefiles",
            index=models.Index(
                fields=["content_type", "object_id"], name="idx_feature_files_type_id"
            ),
        ),
    ]
