# Generated by Django 4.2.17 on 2025-03-12 12:29

import apps.api.models
import apps.api.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0006_remove_featurefiles_idx_feature_files_feature_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('AUTO', 'Automatic Organization'), ('MANUAL', 'User Defined')], default='AUTO', max_length=10)),
                ('folder_structure', models.JSONField(default=dict, help_text="Custom folder structure for different feature types. Example: {'trench': 'trenches', 'node': 'nodes'}")),
            ],
            options={
                'verbose_name': 'Storage Preference',
                'verbose_name_plural': 'Storage Preferences',
            },
        ),
        migrations.AlterField(
            model_name='featurefiles',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'api', 'model__in': ['trench', 'node', 'address', 'residentialunit']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Feature Type'),
        ),
        migrations.AlterField(
            model_name='featurefiles',
            name='file_path',
            field=models.FileField(storage=apps.api.storage.NextcloudStorage(), upload_to=apps.api.models.FeatureFiles.get_upload_path, verbose_name='File Path'),
        ),
    ]
