# Generated by Django 4.2.17 on 2025-09-29 19:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_canvassyncstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesCableType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cable_type', models.TextField(verbose_name='Cable Type')),
                ('fiber_count', models.IntegerField(verbose_name='Fiber Count')),
                ('bundle_count', models.IntegerField(verbose_name='Bundle Count')),
                ('bundle_fiber_count', models.IntegerField(verbose_name='Bundle Fiber Count')),
                ('manufacturer', models.ForeignKey(db_column='manufacturer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributescompany', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Cable Type',
                'verbose_name_plural': 'Cable Types',
                'db_table': 'attributes_cable_type',
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, verbose_name='Cable Name')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('length', models.FloatField(null=True, verbose_name='Length')),
                ('length_total', models.FloatField(null=True, verbose_name='Length Total')),
                ('reserve_at_start', models.IntegerField(null=True, verbose_name='Reserve At Start')),
                ('reserve_at_end', models.IntegerField(null=True, verbose_name='Reserve At End')),
                ('reserve_section', models.IntegerField(null=True, verbose_name='Reserve Section')),
                ('cable_type', models.ForeignKey(db_column='cable_type', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.attributescabletype', verbose_name='Cable Type')),
                ('constructor', models.ForeignKey(db_column='constructor', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructed_cables', to='api.attributescompany', verbose_name='Constructor')),
                ('flag', models.ForeignKey(db_column='flag', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.flags', verbose_name='Flag')),
                ('manufacturer', models.ForeignKey(db_column='manufacturer', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manufactured_cables', to='api.attributescompany', verbose_name='Manufacturer')),
                ('network_level', models.ForeignKey(db_column='network_level', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesnetworklevel', verbose_name='Network Level')),
                ('owner', models.ForeignKey(db_column='owner', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_cables', to='api.attributescompany', verbose_name='Owner')),
                ('project', models.ForeignKey(db_column='project', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.projects', verbose_name='Project')),
                ('status', models.ForeignKey(db_column='status', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesstatus', verbose_name='Status')),
                ('uuid_node_end', models.ForeignKey(db_column='uuid_node_end', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_end_cables', to='api.node', verbose_name='Node End')),
                ('uuid_node_start', models.ForeignKey(db_column='uuid_node_start', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_start_cables', to='api.node', verbose_name='Node Start')),
            ],
            options={
                'verbose_name': 'Cable',
                'verbose_name_plural': 'Cables',
                'db_table': 'cable',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MicroductCableConnection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uuid_cable', models.ForeignKey(db_column='uuid_cable', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.cable', verbose_name='Cable')),
                ('uuid_microduct', models.ForeignKey(db_column='uuid_microduct', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.microduct', verbose_name='Microduct')),
            ],
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['name'], name='idx_cable_name'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['cable_type'], name='idx_cable_cable_type'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['status'], name='idx_cable_status'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['network_level'], name='idx_cable_network_level'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['owner'], name='idx_cable_owner'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['constructor'], name='idx_cable_constructor'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['manufacturer'], name='idx_cable_manufacturer'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['date'], name='idx_cable_date'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['uuid_node_start'], name='idx_cable_uuid_node_start'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['uuid_node_end'], name='idx_cable_uuid_node_end'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['length'], name='idx_cable_length'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['length_total'], name='idx_cable_length_total'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['reserve_at_start'], name='idx_cable_reserve_at_start'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['reserve_at_end'], name='idx_cable_reserve_at_end'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['reserve_section'], name='idx_cable_reserve_section'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['project'], name='idx_cable_project'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['flag'], name='idx_cable_flag'),
        ),
        migrations.AddConstraint(
            model_name='cable',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_cable'),
        ),
    ]
