# Generated by Django 4.2.17 on 2026-01-08 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_remove_live_update_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number_suffix',
            field=models.TextField(blank=True, null=True, verbose_name='House Number Suffix'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id_address',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Address ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='status_development',
            field=models.ForeignKey(blank=True, db_column='status_development', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesstatusdevelopment', verbose_name='Status Development'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='postal_code',
            field=models.TextField(blank=True, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='street',
            field=models.TextField(blank=True, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='attributesconduittype',
            name='conduit_type_alias',
            field=models.TextField(blank=True, null=True, verbose_name='Conduit Type Alias'),
        ),
        migrations.AlterField(
            model_name='attributesconduittype',
            name='conduit_type_microduct',
            field=models.IntegerField(blank=True, null=True, verbose_name='Conduit Type Microduct'),
        ),
        migrations.AlterField(
            model_name='attributesconduittype',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='attributesnodetype',
            name='company',
            field=models.TextField(blank=True, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='attributesnodetype',
            name='dimension',
            field=models.TextField(blank=True, null=True, verbose_name='Dimension'),
        ),
        migrations.AlterField(
            model_name='attributesnodetype',
            name='group',
            field=models.TextField(blank=True, null=True, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='constructor',
            field=models.ForeignKey(blank=True, db_column='constructor', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructed_conduits', to='api.attributescompany', verbose_name='Constructor'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manufactured_conduits', to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='network_level',
            field=models.ForeignKey(blank=True, db_column='network_level', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesnetworklevel', verbose_name='Network Level'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='outer_conduit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_conduits', to='api.attributescompany', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='microduct',
            name='microduct_status',
            field=models.ForeignKey(blank=True, db_column='microduct_status', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.attributesmicroductstatus', verbose_name='Microduct Status'),
        ),
        migrations.AlterField(
            model_name='microduct',
            name='uuid_node',
            field=models.ForeignKey(blank=True, db_column='uuid_node', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.node', verbose_name='Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='constructor',
            field=models.ForeignKey(blank=True, db_column='constructor', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructed_nodes', to='api.attributescompany', verbose_name='Constructor'),
        ),
        migrations.AlterField(
            model_name='node',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='node',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manufactured_nodes', to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='node',
            name='network_level',
            field=models.ForeignKey(blank=True, db_column='network_level', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesnetworklevel', verbose_name='Network Level'),
        ),
        migrations.AlterField(
            model_name='node',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_nodes', to='api.attributescompany', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='node',
            name='uuid_address',
            field=models.ForeignKey(blank=True, db_column='uuid_address', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='node',
            name='warranty',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='qgisproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='construction_depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Construction Depth'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='construction_details',
            field=models.TextField(blank=True, null=True, verbose_name='Construction Details'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='constructor',
            field=models.ForeignKey(blank=True, db_column='constructor', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_trenches', to='api.attributescompany', verbose_name='Constructor'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='funding_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Funding Status'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='house_connection',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='House Connection'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='internal_execution',
            field=models.BooleanField(blank=True, null=True, verbose_name='Internal Execution'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='phase',
            field=models.ForeignKey(blank=True, db_column='phase', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributesphase', verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='trench',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributesstatus', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='NetworkSchemaSettings',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='network_schema_settings', serialize=False, to='api.projects', verbose_name='Project')),
                ('excluded_node_types', models.ManyToManyField(blank=True, help_text='Select node types to exclude from the network schema view.', related_name='excluded_from_schemas', to='api.attributesnodetype', verbose_name='Excluded Node Types')),
            ],
            options={
                'verbose_name': 'Network Schema Settings',
                'verbose_name_plural': 'Network Schema Settings',
                'db_table': 'network_schema_settings',
            },
        ),
    ]
