# Generated by Django 4.2.17 on 2025-09-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_attributescabletype_cable_microductcableconnection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microductcableconnection',
            options={'ordering': ['uuid_microduct', 'uuid_cable'], 'verbose_name': 'Microduct Cable Connection', 'verbose_name_plural': 'Microduct Cable Connections'},
        ),
        migrations.AddIndex(
            model_name='microductcableconnection',
            index=models.Index(fields=['uuid_microduct'], name='idx_md_cable_con_uuid_md'),
        ),
        migrations.AddIndex(
            model_name='microductcableconnection',
            index=models.Index(fields=['uuid_cable'], name='idx_md_cable_con_uuid_cable'),
        ),
        migrations.AddConstraint(
            model_name='microductcableconnection',
            constraint=models.UniqueConstraint(fields=('uuid_microduct', 'uuid_cable'), name='unique_microduct_cable_connection'),
        ),
        migrations.AlterModelTable(
            name='microductcableconnection',
            table='microduct_cable_connection',
        ),
    ]
