# Generated by Django 4.2.17 on 2025-03-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_storagepreferences_alter_featurefiles_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storagepreferences',
            table='storage_preferences',
        ),
    ]
