# Generated by Django 4.2.17 on 2025-09-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_microductcableconnection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='handle_end',
            field=models.CharField(blank=True, help_text='Handle position at end node (top, right, bottom, left)', max_length=10, null=True, verbose_name='Handle End'),
        ),
        migrations.AddField(
            model_name='cable',
            name='handle_start',
            field=models.CharField(blank=True, help_text='Handle position at start node (top, right, bottom, left)', max_length=10, null=True, verbose_name='Handle Start'),
        ),
        migrations.AlterField(
            model_name='attributescabletype',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='constructor',
            field=models.ForeignKey(blank=True, db_column='constructor', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructed_cables', to='api.attributescompany', verbose_name='Constructor'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='length_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Length Total'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='manufacturer',
            field=models.ForeignKey(blank=True, db_column='manufacturer', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manufactured_cables', to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='network_level',
            field=models.ForeignKey(blank=True, db_column='network_level', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesnetworklevel', verbose_name='Network Level'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_cables', to='api.attributescompany', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='reserve_at_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserve At End'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='reserve_at_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserve At Start'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='reserve_section',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserve Section'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='uuid_node_end',
            field=models.ForeignKey(blank=True, db_column='uuid_node_end', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_end_cables', to='api.node', verbose_name='Node End'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='uuid_node_start',
            field=models.ForeignKey(blank=True, db_column='uuid_node_start', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_start_cables', to='api.node', verbose_name='Node Start'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['handle_start'], name='idx_cable_handle_start'),
        ),
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['handle_end'], name='idx_cable_handle_end'),
        ),
    ]
