# Generated by Django 4.2.17 on 2026-01-08 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_olarea_attributesareatype_area_area_unique_area"),
    ]

    operations = [
        migrations.RunSQL("""
    create view public.ol_area as
        select
            a.uuid,
            a.name,
            a.area_type,
            st_transform(a.geom, 3857) as geom,
            a.flag,
            a.project
        from area a
        order by a.name;
    """)
    ]
