# Generated by Django 4.2.17 on 2025-03-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_storagepreferences_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurefiles',
            name='file_type',
            field=models.TextField(null=True, verbose_name='File Type'),
        ),
    ]
