# Generated by Django 4.2.17 on 2025-03-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_featurefiles_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypeCategory',
            fields=[
                ('extension', models.CharField(help_text="File extension without the dot (e.g., 'pdf', 'jpg')", max_length=10, primary_key=True, serialize=False, verbose_name='File Extension')),
                ('category', models.CharField(help_text="Category used for folder organization (e.g., 'photos', 'documents')", max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, help_text='Optional description of this file type', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'File Type Category',
                'verbose_name_plural': 'File Type Categories',
                'db_table': 'file_type_category',
                'ordering': ['extension'],
            },
        ),
    ]
