# Generated by Django 4.2.17 on 2025-10-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cable_handle_end_cable_handle_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='diagram_path',
            field=models.JSONField(blank=True, help_text='Custom waypoints for diagram edge path as array of {x, y} coordinates', null=True, verbose_name='Diagram Path'),
        ),
    ]
