# Generated by Django 4.2.17 on 2026-01-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0009_ol_area_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPackageSchemaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='Name for this configuration', max_length=100, verbose_name='Configuration Name')),
                ('selected_layers', models.JSONField(blank=True, default=list, help_text='List of layer names to include in the GeoPackage schema.', verbose_name='Selected Layers')),
            ],
            options={
                'verbose_name': 'GeoPackage Schema Configuration',
                'verbose_name_plural': 'GeoPackage Schema Configurations',
                'db_table': 'geopackage_schema_config',
            },
        ),
        migrations.AlterField(
            model_name='featurefiles',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'api', 'model__in': ['trench', 'conduit', 'cable', 'node', 'address', 'residentialunit', 'area']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Feature Type'),
        ),
    ]
