# Generated by Django 4.2.17 on 2026-01-10 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_geopackage_schema_config"),
    ]

    operations = [
        migrations.RunSQL(
            """
            alter table area alter column uuid set default gen_random_uuid();
            """
        )
    ]
