# Generated by Django 4.2.17 on 2025-05-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_filetypecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project', models.TextField(verbose_name='Project')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='trench',
            name='project',
            field=models.ForeignKey(db_column='project', db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.projects', verbose_name='Project'),
        ),
    ]
