# Generated by Django 4.2.17 on 2025-10-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cable_diagram_path'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cable',
            index=models.Index(fields=['diagram_path'], name='idx_cable_diagram_path'),
        ),
    ]
