# Generated by Django 4.2.17 on 2025-06-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_projects_trench_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('flag', models.TextField(unique=True, verbose_name='Flag')),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
                'db_table': 'flags',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.TextField(unique=True, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='trench',
            name='flag',
            field=models.ForeignKey(db_column='flag', db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.flags', verbose_name='Flag'),
        ),
    ]
