# Generated by Django 4.2.17 on 2025-10-07 18:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cable_idx_cable_diagram_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableLabel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='The text content to display on the label', verbose_name='Label Text')),
                ('position_x', models.FloatField(blank=True, help_text='X coordinate of the label in the diagram canvas', null=True, verbose_name='Position X')),
                ('position_y', models.FloatField(blank=True, help_text='Y coordinate of the label in the diagram canvas', null=True, verbose_name='Position Y')),
                ('order', models.IntegerField(default=0, help_text='Display order when multiple labels exist', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cable', models.ForeignKey(db_column='cable', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.cable', verbose_name='Cable')),
            ],
            options={
                'verbose_name': 'Cable Label',
                'verbose_name_plural': 'Cable Labels',
                'db_table': 'cable_label',
                'ordering': ['cable', 'order'],
                'indexes': [models.Index(fields=['cable'], name='idx_cable_label_cable'), models.Index(fields=['order'], name='idx_cable_label_order')],
            },
        ),
    ]
