# Generated by Django 4.2.17 on 2026-01-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_wfs_error_triggers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id_address",
            field=models.IntegerField(blank=True, null=True, verbose_name="Address ID"),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.TextField(verbose_name="Area Name"),
        ),
        migrations.AlterField(
            model_name="conduit",
            name="name",
            field=models.TextField(verbose_name="Conduit Name"),
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS unique_address;",
            reverse_sql="""
                CREATE UNIQUE INDEX unique_address 
                ON address (zip_code, street, housenumber, coalesce(house_number_suffix,''));
            """,
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id_address__isnull", False)),
                fields=("project", "id_address"),
                name="unique_address",
            ),
        ),
    ]
