# Generated by Django 4.2.17 on 2025-10-12 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cablelabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesMicroductColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_de', models.CharField(help_text="German color name (e.g., 'rot', 'rot-weiss')", max_length=50, unique=True, verbose_name='German Name')),
                ('name_en', models.CharField(help_text="English color name (e.g., 'red', 'red-white')", max_length=50, verbose_name='English Name')),
                ('hex_code', models.CharField(help_text="Primary CSS hex color code (e.g., '#dc2626')", max_length=7, verbose_name='Hex Color Code')),
                ('hex_code_secondary', models.CharField(blank=True, help_text='Secondary color for striped/two-layer microducts (optional)', max_length=7, null=True, verbose_name='Secondary Hex Color Code')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which colors appear in selection lists', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive colors are hidden but preserved for existing data', verbose_name='Active')),
                ('description', models.TextField(blank=True, help_text='Optional notes about this color', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Microduct Color',
                'verbose_name_plural': 'Microduct Colors',
                'db_table': 'attributes_microduct_color',
                'ordering': ['display_order', 'name_de'],
            },
        ),
        migrations.CreateModel(
            name='ConduitTypeColorMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position', models.IntegerField(help_text='Microduct position/number (1-12, etc.)', verbose_name='Position')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.attributesmicroductcolor', verbose_name='Color')),
                ('conduit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='api.attributesconduittype', verbose_name='Conduit Type')),
            ],
            options={
                'verbose_name': 'Conduit Type Color Mapping',
                'verbose_name_plural': 'Conduit Type Color Mappings',
                'db_table': 'conduit_type_color_mapping',
                'ordering': ['conduit_type', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='attributesmicroductcolor',
            index=models.Index(fields=['name_de'], name='idx_md_color_name_de'),
        ),
        migrations.AddIndex(
            model_name='attributesmicroductcolor',
            index=models.Index(fields=['display_order'], name='idx_md_color_display_order'),
        ),
        migrations.AddIndex(
            model_name='attributesmicroductcolor',
            index=models.Index(fields=['is_active'], name='idx_md_color_is_active'),
        ),
        migrations.AlterUniqueTogether(
            name='conduittypecolormapping',
            unique_together={('conduit_type', 'position')},
        ),
    ]
