# Generated by Django 4.2.17 on 2025-06-12 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_flags_alter_projects_project_trench_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesConduitType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('conduit_type', models.TextField(verbose_name='Conduit Type')),
                ('conduit_count', models.IntegerField(verbose_name='Conduit Count')),
                ('color_code', models.TextField(verbose_name='Color Code')),
                ('conduit_type_alias', models.TextField(null=True, verbose_name='Conduit Type Alias')),
                ('conduit_type_microduct', models.IntegerField(null=True, verbose_name='Conduit Type Microduct')),
            ],
            options={
                'verbose_name': 'Conduit Type',
                'verbose_name_plural': 'Conduit Types',
                'db_table': 'attributes_conduit_type',
            },
        ),
        migrations.CreateModel(
            name='AttributesNetworkLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('network_level', models.TextField(verbose_name='Network Level')),
            ],
            options={
                'verbose_name': 'Network Level',
                'verbose_name_plural': 'Network Levels',
                'db_table': 'attributes_network_level',
            },
        ),
        migrations.CreateModel(
            name='Conduit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('outer_conduit', models.TextField(null=True)),
                ('date', models.DateField(null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Conduit',
                'verbose_name_plural': 'Conduits',
                'db_table': 'conduit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrenchConduitConnection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Trench Conduit Connection',
                'verbose_name_plural': 'Trench Conduit Connections',
                'db_table': 'trench_conduit_connect',
            },
        ),
        migrations.AlterModelOptions(
            name='attributesnodetype',
            options={'verbose_name': 'Node Type', 'verbose_name_plural': 'Node Types'},
        ),
        migrations.RemoveIndex(
            model_name='trench',
            name='idx_trench_company',
        ),
        migrations.RemoveField(
            model_name='trench',
            name='company',
        ),
        migrations.AddField(
            model_name='trench',
            name='constructor',
            field=models.ForeignKey(db_column='constructor', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_trenches', to='api.attributescompany', verbose_name='Constructor'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='city',
            field=models.TextField(null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='company',
            field=models.TextField(verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='email',
            field=models.TextField(null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='housenumber',
            field=models.TextField(null=True, verbose_name='Housenumber'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='phone',
            field=models.TextField(null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='postal_code',
            field=models.TextField(null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='attributescompany',
            name='street',
            field=models.TextField(null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='attributesconstructiontype',
            name='construction_type',
            field=models.TextField(verbose_name='Construction Type'),
        ),
        migrations.AlterField(
            model_name='attributesnodetype',
            name='company',
            field=models.TextField(null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='attributesnodetype',
            name='dimension',
            field=models.TextField(null=True, verbose_name='Dimension'),
        ),
        migrations.AlterField(
            model_name='attributesnodetype',
            name='group',
            field=models.TextField(null=True, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='attributesnodetype',
            name='node_type',
            field=models.TextField(verbose_name='Node Type'),
        ),
        migrations.AlterField(
            model_name='attributesphase',
            name='phase',
            field=models.TextField(verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='attributesstatus',
            name='status',
            field=models.TextField(unique=True, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='trench',
            index=models.Index(fields=['constructor'], name='idx_trench_constructor'),
        ),
        migrations.AddField(
            model_name='trenchconduitconnection',
            name='uuid_conduit',
            field=models.ForeignKey(db_column='uuid_conduit', on_delete=django.db.models.deletion.CASCADE, to='api.conduit', verbose_name='Conduit'),
        ),
        migrations.AddField(
            model_name='trenchconduitconnection',
            name='uuid_trench',
            field=models.ForeignKey(db_column='uuid_trench', on_delete=django.db.models.deletion.CASCADE, to='api.trench', verbose_name='Trench'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='conduit_type',
            field=models.ForeignKey(db_column='conduit_type', on_delete=django.db.models.deletion.CASCADE, to='api.attributesconduittype', verbose_name='Conduit Type'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='constructor',
            field=models.ForeignKey(db_column='constructor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructed_conduits', to='api.attributescompany', verbose_name='Constructor'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='flag',
            field=models.ForeignKey(db_column='flag', on_delete=django.db.models.deletion.DO_NOTHING, to='api.flags', verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='manufacturer',
            field=models.ForeignKey(db_column='manufacturer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manufactured_conduits', to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='network_level',
            field=models.ForeignKey(db_column='network_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesnetworklevel', verbose_name='Network Level'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='owner',
            field=models.ForeignKey(db_column='owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_conduits', to='api.attributescompany', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='project',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.DO_NOTHING, to='api.projects', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='status',
            field=models.ForeignKey(db_column='status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesstatus', verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='attributesnetworklevel',
            index=models.Index(fields=['network_level'], name='idx_network_level_net_level'),
        ),
        migrations.AddField(
            model_name='attributesconduittype',
            name='manufacturer',
            field=models.ForeignKey(db_column='manufacturer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AddIndex(
            model_name='trenchconduitconnection',
            index=models.Index(fields=['uuid_trench'], name='idx_trench_conduit_con_trench'),
        ),
        migrations.AddIndex(
            model_name='trenchconduitconnection',
            index=models.Index(fields=['uuid_conduit'], name='idx_trench_conduit_con_cond'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['name'], name='idx_conduit_name'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['conduit_type'], name='idx_conduit_conduit_type'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['status'], name='idx_conduit_status'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['network_level'], name='idx_conduit_network_level'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['owner'], name='idx_conduit_owner'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['constructor'], name='idx_conduit_constructor'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['manufacturer'], name='idx_conduit_manufacturer'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['project'], name='idx_conduit_project'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['flag'], name='idx_conduit_flag'),
        ),
        migrations.AddIndex(
            model_name='attributesconduittype',
            index=models.Index(fields=['conduit_type'], name='idx_conduit_type_conduit_type'),
        ),
    ]
