# Generated by Django 4.2.17 on 2025-10-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_attributesmicroductcolor_conduittypecolormapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributesconduittype',
            name='color_code',
        ),
    ]
