# Generated by Django 4.2.17 on 2025-06-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_attributesconduittype_attributesnetworklevel_conduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesconduittype',
            name='color_code',
            field=models.JSONField(verbose_name='Color Code'),
        ),
    ]
