# Generated by Django 4.2.17 on 2026-01-11 17:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_remove_fn_id_trench"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipeBranchSettings",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pipe_branch_settings",
                        serialize=False,
                        to="api.projects",
                        verbose_name="Project",
                    ),
                ),
                (
                    "allowed_node_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select node types to include in the pipe-branch node selection.",
                        related_name="allowed_in_pipe_branch",
                        to="api.attributesnodetype",
                        verbose_name="Allowed Node Types",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipe Branch Settings",
                "verbose_name_plural": "Pipe Branch Settings",
                "db_table": "pipe_branch_settings",
            },
        ),
        migrations.CreateModel(
            name="NodeTrenchSelection",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trench_selections",
                        to="api.node",
                        verbose_name="Node",
                    ),
                ),
                (
                    "trench",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_selections",
                        to="api.trench",
                        verbose_name="Trench",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Trench Selection",
                "verbose_name_plural": "Node Trench Selections",
                "db_table": "node_trench_selection",
            },
        ),
        migrations.AddConstraint(
            model_name="nodetrenchselection",
            constraint=models.UniqueConstraint(
                fields=("node", "trench"), name="unique_node_trench_selection"
            ),
        ),
    ]
