# Generated by Django 4.2.17 on 2025-10-13 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_attributesconduittype_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesFiberColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_de', models.CharField(help_text="German color name (e.g., 'rot', 'rot-weiss')", max_length=50, unique=True, verbose_name='German Name')),
                ('name_en', models.CharField(help_text="English color name (e.g., 'red', 'red-white')", max_length=50, verbose_name='English Name')),
                ('hex_code', models.CharField(help_text="Primary CSS hex color code (e.g., '#dc2626')", max_length=7, verbose_name='Hex Color Code')),
                ('hex_code_secondary', models.CharField(blank=True, help_text='Secondary color for striped/two-layer microducts (optional)', max_length=7, null=True, verbose_name='Secondary Hex Color Code')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which colors appear in selection lists', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive colors are hidden but preserved for existing data', verbose_name='Active')),
                ('description', models.TextField(blank=True, help_text='Optional notes about this color', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Fiber Color',
                'verbose_name_plural': 'Fiber Colors',
                'db_table': 'attributes_fiber_color',
                'ordering': ['display_order', 'name_de'],
            },
        ),
        migrations.CreateModel(
            name='AttributesFiberStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fiber_status', models.TextField(unique=True, verbose_name='Fiber Status')),
            ],
            options={
                'verbose_name': 'Fiber Status',
                'verbose_name_plural': 'Fiber Statuses',
                'db_table': 'attributes_fiber_status',
                'ordering': ['fiber_status'],
            },
        ),
        migrations.CreateModel(
            name='Fiber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='The UUID of the fiber', primary_key=True, serialize=False)),
                ('bundle_number', models.IntegerField(help_text='The bundle number that the fiber belongs to', verbose_name='Bundle Number')),
                ('bundle_color', models.TextField(help_text='The color of the bundle that the fiber belongs to', verbose_name='Bundle Color')),
                ('fiber_number_absolute', models.IntegerField(help_text='The absolute fiber number that the fiber belongs to', verbose_name='Fiber Number Absolute')),
                ('fiber_number_in_bundle', models.IntegerField(help_text='The number of the fiber in the bundle that the fiber belongs to', verbose_name='Fiber Number In Bundle')),
                ('fiber_color', models.TextField(help_text='The color of the fiber that the fiber belongs to', verbose_name='Fiber Color')),
                ('active', models.BooleanField(default=True, help_text='Whether the fiber is active', verbose_name='Active')),
                ('fiber_status', models.ForeignKey(blank=True, db_column='fiber_status', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.attributesfiberstatus', verbose_name='Fiber Status')),
                ('flag', models.ForeignKey(db_column='flag', db_index=False, on_delete=django.db.models.deletion.PROTECT, to='api.flags', verbose_name='Flag')),
                ('project', models.ForeignKey(db_column='project', db_index=False, on_delete=django.db.models.deletion.PROTECT, to='api.projects', verbose_name='Project')),
                ('uuid_cable', models.ForeignKey(db_column='uuid_cable', db_index=False, help_text='The cable that the fiber belongs to', on_delete=django.db.models.deletion.PROTECT, to='api.cable', verbose_name='Cable')),
            ],
            options={
                'verbose_name': 'Fiber',
                'verbose_name_plural': 'Fibers',
                'db_table': 'fiber',
                'ordering': ['uuid_cable'],
            },
        ),
        migrations.CreateModel(
            name='CableTypeColorMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position_type', models.CharField(choices=[('bundle', 'Bundle'), ('fiber', 'Fiber')], help_text='Whether this mapping is for bundle or fiber colors', max_length=10, verbose_name='Position Type')),
                ('position', models.IntegerField(help_text='Bundle/Fiber position number (1-12, etc.)', verbose_name='Position')),
                ('cable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='api.attributescabletype', verbose_name='Cable Type')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.attributesfibercolor', verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Cable Type Color Mapping',
                'verbose_name_plural': 'Cable Type Color Mappings',
                'db_table': 'cable_type_color_mapping',
                'ordering': ['cable_type', 'position_type', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='attributesfiberstatus',
            index=models.Index(fields=['fiber_status'], name='idx_fiber_status_status'),
        ),
        migrations.AddIndex(
            model_name='attributesfibercolor',
            index=models.Index(fields=['name_de'], name='idx_fiber_color_name_de'),
        ),
        migrations.AddIndex(
            model_name='attributesfibercolor',
            index=models.Index(fields=['display_order'], name='idx_fiber_color_display_order'),
        ),
        migrations.AddIndex(
            model_name='attributesfibercolor',
            index=models.Index(fields=['is_active'], name='idx_fiber_color_is_active'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['uuid_cable'], name='idx_fiber_cable'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['bundle_number'], name='idx_fiber_bundle_number'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['bundle_color'], name='idx_fiber_bundle_color'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['fiber_number_absolute'], name='idx_fiber_number_absolute'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['fiber_number_in_bundle'], name='idx_fiber_number_in_bundle'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['fiber_color'], name='idx_fiber_fiber_color'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['active'], name='idx_fiber_active'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['fiber_status'], name='idx_fiber_fiber_status'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['flag'], name='idx_fiber_flag'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['project'], name='idx_fiber_project'),
        ),
        migrations.AddIndex(
            model_name='cabletypecolormapping',
            index=models.Index(fields=['cable_type', 'position_type'], name='idx_cable_color_type'),
        ),
        migrations.AlterUniqueTogether(
            name='cabletypecolormapping',
            unique_together={('cable_type', 'position_type', 'position')},
        ),
    ]
