# Generated by Django 4.2.17 on 2025-06-16 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_attributesconduittype_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduit',
            name='conduit_type',
            field=models.ForeignKey(db_column='conduit_type', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.attributesconduittype', verbose_name='Conduit Type'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='constructor',
            field=models.ForeignKey(db_column='constructor', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructed_conduits', to='api.attributescompany', verbose_name='Constructor'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='flag',
            field=models.ForeignKey(db_column='flag', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.flags', verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='manufacturer',
            field=models.ForeignKey(db_column='manufacturer', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manufactured_conduits', to='api.attributescompany', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='name',
            field=models.TextField(unique=True, verbose_name='Conduit Name'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='network_level',
            field=models.ForeignKey(db_column='network_level', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesnetworklevel', verbose_name='Network Level'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='owner',
            field=models.ForeignKey(db_column='owner', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_conduits', to='api.attributescompany', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='project',
            field=models.ForeignKey(db_column='project', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='status',
            field=models.ForeignKey(db_column='status', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.attributesstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trenchconduitconnection',
            name='uuid_conduit',
            field=models.ForeignKey(db_column='uuid_conduit', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.conduit', verbose_name='Conduit'),
        ),
        migrations.AlterField(
            model_name='trenchconduitconnection',
            name='uuid_trench',
            field=models.ForeignKey(db_column='uuid_trench', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.trench', verbose_name='Trench'),
        ),
    ]
