# Generated by Django 4.2.17 on 2025-06-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_conduit_conduit_type_alter_conduit_constructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trench',
            name='id_trench',
            field=models.IntegerField(unique=True, verbose_name='Trench ID'),
        ),
    ]
