# Generated by Django 4.2.17 on 2025-10-13 18:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_attributesfibercolor_attributesfiberstatus_fiber_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="Bundle position number (1, 2, 3, etc.)",
                        verbose_name="Position",
                    ),
                ),
                (
                    "fiber_count",
                    models.IntegerField(
                        help_text="Number of fibers in this bundle",
                        verbose_name="Fiber Count",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bundle",
                "verbose_name_plural": "Bundles",
                "db_table": "bundle",
                "ordering": ["cable_type", "position"],
            },
        ),
        migrations.AlterModelOptions(
            name="fiber",
            options={
                "ordering": ["uuid_cable", "bundle_number", "fiber_number_in_bundle"],
                "verbose_name": "Fiber",
                "verbose_name_plural": "Fibers",
            },
        ),
        migrations.AddField(
            model_name="fiber",
            name="bundle",
            field=models.ForeignKey(
                blank=True,
                db_column="bundle",
                help_text="The bundle that the fiber belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fibers",
                to="api.bundle",
                verbose_name="Bundle",
            ),
        ),
        migrations.AlterField(
            model_name="fiber",
            name="bundle_color",
            field=models.TextField(
                blank=True,
                help_text="DEPRECATED: Use bundle.color instead. The color of the bundle that the fiber belongs to",
                null=True,
                verbose_name="Bundle Color",
            ),
        ),
        migrations.AddIndex(
            model_name="fiber",
            index=models.Index(fields=["bundle"], name="idx_fiber_bundle"),
        ),
        migrations.AddField(
            model_name="bundle",
            name="cable_type",
            field=models.ForeignKey(
                db_column="cable_type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundles",
                to="api.attributescabletype",
                verbose_name="Cable Type",
            ),
        ),
        migrations.AddField(
            model_name="bundle",
            name="color",
            field=models.ForeignKey(
                db_column="color",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.attributesfibercolor",
                verbose_name="Color",
            ),
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(fields=["cable_type"], name="idx_bundle_cable_type"),
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(fields=["position"], name="idx_bundle_position"),
        ),
        migrations.AlterUniqueTogether(
            name="bundle",
            unique_together={("cable_type", "position")},
        ),
    ]
