"""
Migration to change id_trench from GENERATED ALWAYS to GENERATED BY DEFAULT.

This allows WFS clients to insert rows with NULL for id_trench,
which PostgreSQL will then auto-generate. GENERATED ALWAYS rejects
explicit NULL values, while GENERATED BY DEFAULT treats NULL as
"generate the value for me".
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_pipebranchsettings_nodetrenchselection_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE trench
            ALTER COLUMN id_trench
            SET GENERATED BY DEFAULT;
            """,
            reverse_sql="""
            ALTER TABLE trench
            ALTER COLUMN id_trench
            SET GENERATED ALWAYS;
            """,
        ),
    ]
