# Generated by Django 4.2.17 on 2025-10-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_bundle_alter_fiber_options_alter_fiber_bundle_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together={('cable_type', 'position', 'color')},
        ),
    ]
