# Generated by Django 4.2.17 on 2026-01-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_change_id_trench_to_generated_by_default"),
    ]

    operations = [
        # Add geom_3857 generated column to trench (LineString)
        migrations.RunSQL(
            sql="""
            ALTER TABLE trench
            ADD COLUMN geom_3857 geometry(LineString, 3857)
            GENERATED ALWAYS AS (ST_Transform(geom, 3857)) STORED;
            """,
            reverse_sql="""
            ALTER TABLE trench DROP COLUMN IF EXISTS geom_3857;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_trench_geom_3857 ON trench USING GIST (geom_3857);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_trench_geom_3857;
            """,
        ),
        # Add geom_3857 generated column to node (Point)
        migrations.RunSQL(
            sql="""
            ALTER TABLE node
            ADD COLUMN geom_3857 geometry(Point, 3857)
            GENERATED ALWAYS AS (ST_Transform(geom, 3857)) STORED;
            """,
            reverse_sql="""
            ALTER TABLE node DROP COLUMN IF EXISTS geom_3857;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_node_geom_3857 ON node USING GIST (geom_3857);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_node_geom_3857;
            """,
        ),
        # Add geom_3857 generated column to address (Point)
        migrations.RunSQL(
            sql="""
            ALTER TABLE address
            ADD COLUMN geom_3857 geometry(Point, 3857)
            GENERATED ALWAYS AS (ST_Transform(geom, 3857)) STORED;
            """,
            reverse_sql="""
            ALTER TABLE address DROP COLUMN IF EXISTS geom_3857;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_address_geom_3857 ON address USING GIST (geom_3857);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_address_geom_3857;
            """,
        ),
        # Add geom_3857 generated column to area (Polygon)
        migrations.RunSQL(
            sql="""
            ALTER TABLE area
            ADD COLUMN geom_3857 geometry(Polygon, 3857)
            GENERATED ALWAYS AS (ST_Transform(geom, 3857)) STORED;
            """,
            reverse_sql="""
            ALTER TABLE area DROP COLUMN IF EXISTS geom_3857;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_area_geom_3857 ON area USING GIST (geom_3857);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_area_geom_3857;
            """,
        ),
        # Run ANALYZE on all tables to update statistics
        migrations.RunSQL(
            sql="""
            ANALYZE trench, node, address, area;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
