# Generated by Django 4.2.17 on 2026-01-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_add_geom_3857_columns"),
    ]

    operations = [
        # Add project index for trench
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_trench_project ON trench (project);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_trench_project;
            """,
        ),
        # Add project index for node
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_node_project ON node (project);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_node_project;
            """,
        ),
        # Add project index for area
        migrations.RunSQL(
            sql="""
            CREATE INDEX idx_area_project ON area (project);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_area_project;
            """,
        ),
        # Update statistics
        migrations.RunSQL(
            sql="""
            ANALYZE trench, node, area;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
