# Generated by Django 4.2.17 on 2025-10-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_bundle_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='cable_type',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='color',
        ),
        migrations.RemoveIndex(
            model_name='fiber',
            name='idx_fiber_bundle',
        ),
        migrations.RemoveField(
            model_name='fiber',
            name='bundle',
        ),
        migrations.AlterField(
            model_name='fiber',
            name='bundle_color',
            field=models.TextField(help_text='The color of the bundle that the fiber belongs to', verbose_name='Bundle Color'),
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
