# Generated by Django 4.2.17 on 2026-01-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_add_project_indexes"),
    ]

    operations = [
        # Drop existing views (CASCADE handles any dependencies)
        migrations.RunSQL(
            sql="""
            DROP VIEW IF EXISTS public.ol_trench CASCADE;
            DROP VIEW IF EXISTS public.ol_node CASCADE;
            DROP VIEW IF EXISTS public.ol_address CASCADE;
            DROP VIEW IF EXISTS public.ol_area CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Recreate ol_trench using geom_3857 directly
        migrations.RunSQL(
            sql="""
            CREATE VIEW public.ol_trench AS
            SELECT
                t.uuid,
                t.id_trench,
                t.construction_depth,
                t.construction_details,
                t.internal_execution,
                t.funding_status,
                t.date,
                t.comment,
                t.house_connection,
                t.length,
                t.geom_3857 AS geom,
                t.constructor,
                t.construction_type,
                t.owner,
                t.phase,
                t.status,
                t.surface,
                t.project,
                t.flag
            FROM trench t
            ORDER BY t.id_trench;
            """,
            reverse_sql="""
            DROP VIEW IF EXISTS public.ol_trench;
            CREATE VIEW public.ol_trench AS
            SELECT
                t.uuid,
                t.id_trench,
                t.construction_depth,
                t.construction_details,
                t.internal_execution,
                t.funding_status,
                t.date,
                t.comment,
                t.house_connection,
                t.length,
                ST_Transform(t.geom, 3857) AS geom,
                t.constructor,
                t.construction_type,
                t.owner,
                t.phase,
                t.status,
                t.surface,
                t.project,
                t.flag
            FROM trench t
            ORDER BY t.id_trench;
            """,
        ),
        # Recreate ol_node using geom_3857 directly
        migrations.RunSQL(
            sql="""
            CREATE VIEW public.ol_node AS
            SELECT
                n.uuid,
                n.name,
                n.warranty,
                n.date,
                n.geom_3857 AS geom,
                n.constructor,
                n.flag,
                n.manufacturer,
                n.network_level,
                n.node_type,
                n.owner,
                n.project,
                n.status,
                n.uuid_address
            FROM node n;
            """,
            reverse_sql="""
            DROP VIEW IF EXISTS public.ol_node;
            CREATE VIEW public.ol_node AS
            SELECT
                n.uuid,
                n.name,
                n.warranty,
                n.date,
                ST_Transform(n.geom, 3857) AS geom,
                n.constructor,
                n.flag,
                n.manufacturer,
                n.network_level,
                n.node_type,
                n.owner,
                n.project,
                n.status,
                n.uuid_address
            FROM node n;
            """,
        ),
        # Recreate ol_address using geom_3857 directly
        migrations.RunSQL(
            sql="""
            CREATE VIEW public.ol_address AS
            SELECT
                a.uuid,
                a.id_address,
                a.zip_code,
                a.city,
                a.district,
                a.street,
                a.housenumber,
                a.house_number_suffix,
                a.geom_3857 AS geom,
                a.flag,
                a.project,
                a.status_development
            FROM address a;
            """,
            reverse_sql="""
            DROP VIEW IF EXISTS public.ol_address;
            CREATE VIEW public.ol_address AS
            SELECT
                a.uuid,
                a.id_address,
                a.zip_code,
                a.city,
                a.district,
                a.street,
                a.housenumber,
                a.house_number_suffix,
                ST_Transform(a.geom, 3857) AS geom,
                a.flag,
                a.project,
                a.status_development
            FROM address a;
            """,
        ),
        # Recreate ol_area using geom_3857 directly
        migrations.RunSQL(
            sql="""
            CREATE VIEW public.ol_area AS
            SELECT
                a.uuid,
                a.name,
                a.area_type,
                a.geom_3857 AS geom,
                a.flag,
                a.project
            FROM area a
            ORDER BY a.name;
            """,
            reverse_sql="""
            DROP VIEW IF EXISTS public.ol_area;
            CREATE VIEW public.ol_area AS
            SELECT
                a.uuid,
                a.name,
                a.area_type,
                ST_Transform(a.geom, 3857) AS geom,
                a.flag,
                a.project
            FROM area a
            ORDER BY a.name;
            """,
        ),
    ]
