# Generated by Django 4.2.17 on 2025-10-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_bundle_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabletypecolormapping',
            name='layer',
            field=models.TextField(choices=[('inner', 'Inner'), ('outer', 'Outer')], default='inner', help_text='Inner or outer layer', verbose_name='Layer'),
        ),
        migrations.AlterField(
            model_name='fiber',
            name='uuid_cable',
            field=models.ForeignKey(db_column='uuid_cable', db_index=False, help_text='The cable that the fiber belongs to', on_delete=django.db.models.deletion.CASCADE, to='api.cable', verbose_name='Cable'),
        ),
    ]
