# Generated by Django 4.2.17 on 2025-10-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_cabletypecolormapping_layer_alter_fiber_uuid_cable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiber',
            options={'ordering': ['uuid_cable', 'fiber_number_absolute', 'bundle_number', 'fiber_number_in_bundle'], 'verbose_name': 'Fiber', 'verbose_name_plural': 'Fibers'},
        ),
        migrations.AddField(
            model_name='fiber',
            name='layer',
            field=models.TextField(default='inner', help_text='Inner or outer layer', verbose_name='Layer'),
        ),
        migrations.AddIndex(
            model_name='fiber',
            index=models.Index(fields=['layer'], name='idx_fiber_layer'),
        ),
    ]
