"""
Migration to add a trigger that auto-generates id_trench when NULL is provided.

WFS inserts explicitly include id_trench=NULL in the INSERT statement.
PostgreSQL's GENERATED BY DEFAULT only works when the column is omitted,
not when explicitly set to NULL. This trigger handles that case.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_update_views_geom_3857"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION fn_generate_id_trench_if_null()
            RETURNS trigger
            LANGUAGE plpgsql AS
            $$
            BEGIN
                IF NEW.id_trench IS NULL THEN
                    NEW.id_trench := nextval(pg_get_serial_sequence('trench', 'id_trench'));
                END IF;
                RETURN NEW;
            END;
            $$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS fn_generate_id_trench_if_null();",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER tg_00_generate_id_trench_if_null
                BEFORE INSERT
                ON trench
                FOR EACH ROW
            EXECUTE FUNCTION fn_generate_id_trench_if_null();
            """,
            reverse_sql="DROP TRIGGER IF EXISTS tg_00_generate_id_trench_if_null ON trench;",
        ),
    ]
