# Generated by Django 4.2.17 on 2025-10-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_fiber_options_fiber_layer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagepreferences',
            name='mode',
            field=models.CharField(choices=[('AUTO', 'Automatic Organization')], default='AUTO', max_length=10),
        ),
    ]
