# Generated by Django 4.2.17 on 2026-01-14 20:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_id_trench_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesComponentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.TextField(help_text="The type of the component (e.g. 'Router', 'Switch', 'Access Point', etc.)", unique=True, verbose_name='Component Type')),
                ('occupied_slots', models.IntegerField(default=1, help_text='Number of slots occupied by the component (default: 1)', verbose_name='Occupied Slots')),
                ('manufacturer', models.ForeignKey(blank=True, db_column='manufacturer', help_text='The manufacturer of the component', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.attributescompany', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Component Type',
                'verbose_name_plural': 'Component Types',
                'db_table': 'attributes_component_type',
                'ordering': ['component_type'],
            },
        ),
        migrations.CreateModel(
            name='NodeSlotConfiguration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('side', models.CharField(help_text="The name of the side (e.g., 'A', 'B', 'Left Side', 'Right Side')", max_length=50, verbose_name='Side')),
                ('total_slots', models.IntegerField(help_text='The total number of slots available on this side', verbose_name='Total Slots')),
                ('uuid_node', models.ForeignKey(db_column='uuid_node', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='slot_configurations', to='api.node', verbose_name='Node')),
            ],
            options={
                'verbose_name': 'Node Slot Configuration',
                'verbose_name_plural': 'Node Slot Configurations',
                'db_table': 'node_slot_configuration',
                'ordering': ['uuid_node', 'side'],
            },
        ),
        migrations.CreateModel(
            name='AttributesComponentStructure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('in_or_out', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10, verbose_name='In or Out')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('port_alias', models.TextField(blank=True, null=True, verbose_name='Port In Alias')),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributescomponenttype', verbose_name='Component Type')),
            ],
            options={
                'verbose_name': 'Component Structure',
                'verbose_name_plural': 'Component Structures',
                'db_table': 'attributes_component_structure',
                'ordering': ['component_type', 'in_or_out', 'port'],
            },
        ),
        migrations.CreateModel(
            name='NodeStructure',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slot_start', models.IntegerField(help_text='The start slot of the component in the node', verbose_name='Slot Start')),
                ('slot_end', models.IntegerField(help_text='The end slot of the component in the node', verbose_name='Slot End')),
                ('clip_number', models.IntegerField(blank=True, help_text='The number of the clip in the component', null=True, verbose_name='Clip Slot Number')),
                ('purpose', models.CharField(choices=[('component', 'Component'), ('reserve', 'Reserve'), ('empty', 'Empty')], default='component', help_text='The purpose of this slot range (component, reserve, or empty)', max_length=20, verbose_name='Purpose')),
                ('label', models.CharField(blank=True, help_text="Optional label for this slot range (e.g., 'Reserve for future use')", max_length=100, null=True, verbose_name='Label')),
                ('component_structure', models.ForeignKey(blank=True, db_column='component_structure', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributescomponentstructure', verbose_name='Component Structure')),
                ('component_type', models.ForeignKey(blank=True, db_column='component_type', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributescomponenttype', verbose_name='Component Type')),
                ('slot_configuration', models.ForeignKey(db_column='slot_configuration', db_index=False, help_text='The slot configuration (side) where this structure is placed', on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='api.nodeslotconfiguration', verbose_name='Slot Configuration')),
                ('uuid_node', models.ForeignKey(db_column='uuid_node', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='api.node', verbose_name='Node')),
            ],
            options={
                'verbose_name': 'Node Structure',
                'verbose_name_plural': 'Node Structures',
                'db_table': 'node_structure',
                'ordering': ['uuid_node', 'slot_configuration', 'slot_start'],
                'indexes': [models.Index(fields=['uuid_node'], name='idx_node_structure_node'), models.Index(fields=['slot_configuration'], name='idx_node_structure_slot_config'), models.Index(fields=['component_type'], name='idx_node_structure_comp_type'), models.Index(fields=['component_structure'], name='idx_node_component_structure'), models.Index(fields=['purpose'], name='idx_node_structure_purpose')],
            },
        ),
        migrations.AddConstraint(
            model_name='nodestructure',
            constraint=models.UniqueConstraint(fields=('slot_configuration', 'slot_start', 'slot_end'), name='unique_node_structure_slot'),
        ),
        migrations.AddIndex(
            model_name='nodeslotconfiguration',
            index=models.Index(fields=['uuid_node'], name='idx_node_slot_config_node'),
        ),
        migrations.AddConstraint(
            model_name='nodeslotconfiguration',
            constraint=models.UniqueConstraint(fields=('uuid_node', 'side'), name='unique_node_slot_config_side'),
        ),
        migrations.AddIndex(
            model_name='attributescomponenttype',
            index=models.Index(fields=['component_type'], name='idx_component_type'),
        ),
        migrations.AddIndex(
            model_name='attributescomponentstructure',
            index=models.Index(fields=['component_type', 'in_or_out', 'port'], name='idx_component_structure_type'),
        ),
        migrations.AddConstraint(
            model_name='attributescomponentstructure',
            constraint=models.UniqueConstraint(fields=('component_type', 'in_or_out', 'port'), name='unique_component_structure'),
        ),
    ]
