# Generated by Django 4.2.17 on 2025-10-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0021_alter_storagepreferences_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurefiles',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'api', 'model__in': ['trench', 'conduit', 'cable', 'node', 'address', 'residentialunit']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Feature Type'),
        ),
    ]
