# Generated by Django 4.2.17 on 2026-01-16 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_container_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['uuid_node', 'sort_order'], 'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='nodeslotconfiguration',
            options={'ordering': ['uuid_node', 'sort_order', 'side'], 'verbose_name': 'Node Slot Configuration', 'verbose_name_plural': 'Node Slot Configurations'},
        ),
        migrations.AlterField(
            model_name='attributescomponentstructure',
            name='port_alias',
            field=models.TextField(blank=True, null=True, verbose_name='Port Alias'),
        ),
        migrations.CreateModel(
            name='NodeSlotDivider',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('after_slot', models.IntegerField(help_text='The slot number after which this divider appears', verbose_name='After Slot')),
                ('slot_configuration', models.ForeignKey(db_column='slot_configuration', help_text='The slot configuration this divider belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dividers', to='api.nodeslotconfiguration', verbose_name='Slot Configuration')),
            ],
            options={
                'verbose_name': 'Node Slot Divider',
                'verbose_name_plural': 'Node Slot Dividers',
                'db_table': 'node_slot_divider',
                'ordering': ['slot_configuration', 'after_slot'],
            },
        ),
        migrations.CreateModel(
            name='NodeSlotClipNumber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slot_number', models.IntegerField(help_text='The slot number this clip number is assigned to', verbose_name='Slot Number')),
                ('clip_number', models.CharField(help_text="The custom clip number label (e.g., '1', '1A', '2B')", max_length=20, verbose_name='Clip Number')),
                ('slot_configuration', models.ForeignKey(db_column='slot_configuration', help_text='The slot configuration this clip number belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='clip_numbers', to='api.nodeslotconfiguration', verbose_name='Slot Configuration')),
            ],
            options={
                'verbose_name': 'Node Slot Clip Number',
                'verbose_name_plural': 'Node Slot Clip Numbers',
                'db_table': 'node_slot_clip_number',
                'ordering': ['slot_configuration', 'slot_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='nodeslotdivider',
            constraint=models.UniqueConstraint(fields=('slot_configuration', 'after_slot'), name='unique_slot_divider'),
        ),
        migrations.AddConstraint(
            model_name='nodeslotclipnumber',
            constraint=models.UniqueConstraint(fields=('slot_configuration', 'slot_number'), name='unique_slot_clip_number'),
        ),
    ]
