# Generated by Django 4.2.17 on 2025-11-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_featurefiles_content_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='featurefiles',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'file_path'), name='unique_feature_file_path'),
        ),
    ]
