# Generated by Django 4.2.17 on 2026-01-18 10:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_node_slot_divider_and_clip_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberSplice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('port_number', models.PositiveIntegerField(help_text='The port number on the component (e.g., 1-12 for a splice cassette)', verbose_name='Port Number')),
                ('node_structure', models.ForeignKey(db_column='node_structure', help_text='The component placement this splice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fiber_splices', to='api.nodestructure', verbose_name='Node Structure')),
                ('fiber_a', models.ForeignKey(blank=True, db_column='fiber_a', help_text='First fiber in this splice connection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='splices_as_a', to='api.fiber', verbose_name='Fiber A')),
                ('cable_a', models.ForeignKey(blank=True, db_column='cable_a', help_text='The cable of fiber A (denormalized for CASCADE delete)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_splices_as_a', to='api.cable', verbose_name='Cable A')),
                ('fiber_b', models.ForeignKey(blank=True, db_column='fiber_b', help_text='Second fiber in this splice connection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='splices_as_b', to='api.fiber', verbose_name='Fiber B')),
                ('cable_b', models.ForeignKey(blank=True, db_column='cable_b', help_text='The cable of fiber B (denormalized for CASCADE delete)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_splices_as_b', to='api.cable', verbose_name='Cable B')),
            ],
            options={
                'verbose_name': 'Fiber Splice',
                'verbose_name_plural': 'Fiber Splices',
                'db_table': 'fiber_splice',
                'ordering': ['node_structure', 'port_number'],
            },
        ),
        migrations.AddIndex(
            model_name='fibersplice',
            index=models.Index(fields=['node_structure'], name='idx_fiber_splice_node_struct'),
        ),
        migrations.AddIndex(
            model_name='fibersplice',
            index=models.Index(fields=['fiber_a'], name='idx_fiber_splice_fiber_a'),
        ),
        migrations.AddIndex(
            model_name='fibersplice',
            index=models.Index(fields=['fiber_b'], name='idx_fiber_splice_fiber_b'),
        ),
        migrations.AddIndex(
            model_name='fibersplice',
            index=models.Index(fields=['cable_a'], name='idx_fiber_splice_cable_a'),
        ),
        migrations.AddIndex(
            model_name='fibersplice',
            index=models.Index(fields=['cable_b'], name='idx_fiber_splice_cable_b'),
        ),
        migrations.AddConstraint(
            model_name='fibersplice',
            constraint=models.UniqueConstraint(fields=('node_structure', 'port_number'), name='unique_fiber_splice_port'),
        ),
    ]
