# Generated by Django 4.2.17 on 2025-11-07 20:54

import apps.api.models
import apps.api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_featurefiles_unique_feature_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GtPkMetadata',
        ),
        migrations.AlterField(
            model_name='featurefiles',
            name='file_path',
            field=models.FileField(max_length=254, storage=apps.api.storage.LocalMediaStorage(), upload_to=apps.api.models.FeatureFiles.get_upload_path, verbose_name='File Path'),
        ),
    ]
