# Generated by Django 4.2.17 on 2025-11-10 07:27

import apps.api.models
import apps.api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_gtpkmetadata_alter_featurefiles_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurefiles',
            name='file_path',
            field=models.FileField(max_length=500, storage=apps.api.storage.LocalMediaStorage(), upload_to=apps.api.models.FeatureFiles.get_upload_path, verbose_name='File Path'),
        ),
    ]
