# Generated by Django 4.2.17 on 2025-11-10 08:05

import apps.api.models
import apps.api.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_alter_featurefiles_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='QGISProject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.SlugField(help_text="Slug-like identifier used in WMS/WFS URLs (e.g., 'infrastructure', 'public-map')", max_length=100, unique=True, verbose_name='Project Name')),
                ('display_name', models.CharField(help_text='Human-readable project name', max_length=200, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of this QGIS project', verbose_name='Description')),
                ('project_file', models.FileField(help_text='QGIS project file (.qgs or .qgz)', storage=apps.api.storage.QGISProjectStorage(), upload_to=apps.api.models.QGISProject.get_qgis_upload_path, verbose_name='Project File')),
                ('is_default', models.BooleanField(default=False, help_text='Default project used when no PROJECT parameter is specified in WMS/WFS requests', verbose_name='Default Project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'QGIS Project',
                'verbose_name_plural': 'QGIS Projects',
                'db_table': 'qgis_projects',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
