# Generated by Django 4.2.17 on 2025-11-10 10:44

import apps.api.models
import apps.api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_qgisproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qgisproject',
            options={'ordering': ['display_name', '-created_at'], 'verbose_name': 'QGIS Project', 'verbose_name_plural': 'QGIS Projects'},
        ),
        migrations.RemoveField(
            model_name='qgisproject',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='qgisproject',
            name='project_file',
            field=models.FileField(help_text='QGIS project file (.qgs or .qgz)', storage=apps.api.storage.QGISProjectStorage(), upload_to=apps.api.models.QGISProject.get_qgis_upload_path, verbose_name='QGIS Project File'),
        ),
    ]
