# Generated by Django 4.2.17 on 2025-11-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0027_alter_qgisproject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=20, verbose_name='Log Level')),
                ('logger_name', models.CharField(help_text="Name of the logger (e.g., 'apps.api', 'frontend.auth')", max_length=255, verbose_name='Logger Name')),
                ('message', models.TextField(help_text='The log message', verbose_name='Message')),
                ('source', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], db_index=True, default='backend', help_text='Whether this log came from backend or frontend', max_length=50, verbose_name='Source')),
                ('path', models.CharField(blank=True, help_text='Request path or URL where the log occurred', max_length=500, null=True, verbose_name='Path')),
                ('extra_data', models.JSONField(blank=True, help_text='Additional context data (request method, IP, user agent, etc.)', null=True, verbose_name='Extra Data')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'db_table': 'log_entry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_log_entry_timestamp'), models.Index(fields=['level'], name='idx_log_entry_level'), models.Index(fields=['user'], name='idx_log_entry_user'), models.Index(fields=['source'], name='idx_log_entry_source'), models.Index(fields=['logger_name'], name='idx_log_entry_logger_name')],
            },
        ),
    ]
