# Generated by Django 4.2.17 on 2025-11-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project associated with this log entry (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.projects', verbose_name='Project'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['project'], name='idx_log_entry_project'),
        ),
    ]
