# Generated by Django 5.2.10 on 2026-02-06 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_attributesresidentialunitstatus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="residentialunit",
            name="suffix",
        ),
    ]
