# Generated by Django 5.2.10 on 2026-02-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_trench_id_alphanumeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkschemasettings',
            name='child_view_enabled_node_types',
            field=models.ManyToManyField(blank=True, help_text="Node types that show the 'View Building Connections' button.", related_name='child_view_enabled_schemas', to='api.attributesnodetype', verbose_name='Child View Enabled Node Types'),
        ),
    ]
