# Generated by Django 5.2.10 on 2026-02-22 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_cable_parent_node_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMSLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Layer Name')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Layer Title')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'WMS Layer',
                'verbose_name_plural': 'WMS Layers',
                'db_table': 'wms_layer',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WMSSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(max_length=500, verbose_name='WMS URL')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('_password', models.BinaryField(blank=True, null=True, verbose_name='Password (encrypted)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'WMS Source',
                'verbose_name_plural': 'WMS Sources',
                'db_table': 'wms_source',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='wmssource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wms_sources', to='api.projects', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='api.wmssource', verbose_name='WMS Source'),
        ),
        migrations.AlterUniqueTogether(
            name='wmslayer',
            unique_together={('source', 'name')},
        ),
    ]
