# Generated by Django 5.2.10 on 2026-02-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_wms_models"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS public.qgis_trench;",
            reverse_sql="""
            CREATE VIEW public.qgis_trench AS
                SELECT
                    id_trench,
                    construction_type,
                    surface,
                    flag,
                    project,
                    geom
                FROM public.trench;
            """,
        ),
        migrations.AddField(
            model_name="wmslayer",
            name="max_zoom",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum zoom level (0-22, blank = no limit)",
                null=True,
                verbose_name="Maximum Zoom",
            ),
        ),
        migrations.AddField(
            model_name="wmslayer",
            name="min_zoom",
            field=models.IntegerField(
                default=8,
                help_text="Minimum zoom level (0-22)",
                verbose_name="Minimum Zoom",
            ),
        ),
        migrations.AddField(
            model_name="wmslayer",
            name="opacity",
            field=models.FloatField(
                default=1.0,
                help_text="0.0 = transparent, 1.0 = opaque",
                verbose_name="Opacity",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="trench",
                    name="id_trench",
                    field=models.CharField(max_length=10, verbose_name="Trench ID"),
                ),
                migrations.AddConstraint(
                    model_name="trench",
                    constraint=models.UniqueConstraint(
                        fields=("project", "id_trench"),
                        name="unique_trench_id_per_project",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
