# Generated by Django 5.2.10 on 2026-02-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_wmslayer_zoom_opacity"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["flag"], name="idx_area_flag"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["project", "flag"], name="idx_area_project_flag"
            ),
        ),
        migrations.AddIndex(
            model_name="trench",
            index=models.Index(fields=["flag"], name="idx_trench_flag"),
        ),
        migrations.AddIndex(
            model_name="trench",
            index=models.Index(
                fields=["project", "flag"], name="idx_trench_project_flag"
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="area",
                    index=models.Index(fields=["project"], name="idx_area_project"),
                ),
                migrations.AddIndex(
                    model_name="node",
                    index=models.Index(fields=["project"], name="idx_node_project"),
                ),
                migrations.AddIndex(
                    model_name="trench",
                    index=models.Index(fields=["project"], name="idx_trench_project"),
                ),
            ],
            database_operations=[],
        ),
    ]
