# Generated by Django 5.2.10 on 2026-02-23 20:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_area_idx_area_project_area_idx_area_flag_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAddress",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "id_address",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Address ID"
                    ),
                ),
                ("zip_code", models.TextField(verbose_name="Zip Code")),
                ("city", models.TextField(verbose_name="City")),
                (
                    "district",
                    models.TextField(blank=True, null=True, verbose_name="District"),
                ),
                ("street", models.TextField(verbose_name="Street")),
                ("housenumber", models.IntegerField(verbose_name="Housenumber")),
                (
                    "house_number_suffix",
                    models.TextField(
                        blank=True, null=True, verbose_name="House Number Suffix"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=25832, verbose_name="Geometry"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.flags",
                        verbose_name="Flag",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="project",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.projects",
                        verbose_name="Project",
                    ),
                ),
                (
                    "status_development",
                    models.ForeignKey(
                        blank=True,
                        db_column="status_development",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesstatusdevelopment",
                        verbose_name="Status Development",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Address",
                "verbose_name_plural": "historical Addresses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalArea",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("name", models.TextField(verbose_name="Area Name")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=25832, verbose_name="Geometry"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "area_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="area_type",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesareatype",
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.flags",
                        verbose_name="Flag",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="project",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.projects",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Area",
                "verbose_name_plural": "historical Areas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCable",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("name", models.TextField(db_index=True, verbose_name="Cable Name")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                (
                    "length",
                    models.FloatField(blank=True, null=True, verbose_name="Length"),
                ),
                (
                    "length_total",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Length Total"
                    ),
                ),
                (
                    "reserve_at_start",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Reserve At Start"
                    ),
                ),
                (
                    "reserve_at_end",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Reserve At End"
                    ),
                ),
                (
                    "reserve_section",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Reserve Section"
                    ),
                ),
                (
                    "handle_start",
                    models.CharField(
                        blank=True,
                        help_text="Handle position at start node (top, right, bottom, left)",
                        max_length=10,
                        null=True,
                        verbose_name="Handle Start",
                    ),
                ),
                (
                    "handle_end",
                    models.CharField(
                        blank=True,
                        help_text="Handle position at end node (top, right, bottom, left)",
                        max_length=10,
                        null=True,
                        verbose_name="Handle End",
                    ),
                ),
                (
                    "diagram_path",
                    models.JSONField(
                        blank=True,
                        help_text="Custom waypoints for diagram edge path as array of {x, y} coordinates",
                        null=True,
                        verbose_name="Diagram Path",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cable_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="cable_type",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescabletype",
                        verbose_name="Cable Type",
                    ),
                ),
                (
                    "constructor",
                    models.ForeignKey(
                        blank=True,
                        db_column="constructor",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Constructor",
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.flags",
                        verbose_name="Flag",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        db_column="manufacturer",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Manufacturer",
                    ),
                ),
                (
                    "network_level",
                    models.ForeignKey(
                        blank=True,
                        db_column="network_level",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesnetworklevel",
                        verbose_name="Network Level",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Owner",
                    ),
                ),
                (
                    "parent_node_context",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_node_context",
                        db_constraint=False,
                        help_text="If set, cable was created in child view of this parent node",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.node",
                        verbose_name="Parent Node Context",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="project",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.projects",
                        verbose_name="Project",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_column="status",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesstatus",
                        verbose_name="Status",
                    ),
                ),
                (
                    "uuid_node_end",
                    models.ForeignKey(
                        blank=True,
                        db_column="uuid_node_end",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.node",
                        verbose_name="Node End",
                    ),
                ),
                (
                    "uuid_node_start",
                    models.ForeignKey(
                        blank=True,
                        db_column="uuid_node_start",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.node",
                        verbose_name="Node Start",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Cable",
                "verbose_name_plural": "historical Cables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalConduit",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("name", models.TextField(verbose_name="Conduit Name")),
                ("outer_conduit", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "conduit_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="conduit_type",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesconduittype",
                        verbose_name="Conduit Type",
                    ),
                ),
                (
                    "constructor",
                    models.ForeignKey(
                        blank=True,
                        db_column="constructor",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Constructor",
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.flags",
                        verbose_name="Flag",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        db_column="manufacturer",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Manufacturer",
                    ),
                ),
                (
                    "network_level",
                    models.ForeignKey(
                        blank=True,
                        db_column="network_level",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesnetworklevel",
                        verbose_name="Network Level",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Owner",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="project",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.projects",
                        verbose_name="Project",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_column="status",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesstatus",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Conduit",
                "verbose_name_plural": "historical Conduits",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContainer",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom name for this container instance",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order of this container among siblings",
                        verbose_name="Sort Order",
                    ),
                ),
                (
                    "is_expanded",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this container is expanded in the UI",
                        verbose_name="Expanded",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "container_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="container_type",
                        db_constraint=False,
                        help_text="The type of this container",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.containertype",
                        verbose_name="Container Type",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_container",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_container",
                        db_constraint=False,
                        help_text="The parent container (null if top-level)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.container",
                        verbose_name="Parent Container",
                    ),
                ),
                (
                    "uuid_node",
                    models.ForeignKey(
                        blank=True,
                        db_column="uuid_node",
                        db_constraint=False,
                        help_text="The node this container belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.node",
                        verbose_name="Node",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Container",
                "verbose_name_plural": "historical Containers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContainerType",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the container type (e.g., 'MFG-Door-Left', '19-inch Rack')",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this container type",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon identifier for frontend display (e.g., 'folder', 'server')",
                        max_length=50,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Optional hex color code for visual distinction (e.g., '#3B82F6')",
                        max_length=7,
                        null=True,
                        verbose_name="Color",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which this type appears in selection dropdowns",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this container type is available for use",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Container Type",
                "verbose_name_plural": "historical Container Types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFiber",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="The UUID of the fiber",
                    ),
                ),
                (
                    "bundle_number",
                    models.IntegerField(
                        help_text="The bundle number that the fiber belongs to",
                        verbose_name="Bundle Number",
                    ),
                ),
                (
                    "bundle_color",
                    models.TextField(
                        help_text="The color of the bundle that the fiber belongs to",
                        verbose_name="Bundle Color",
                    ),
                ),
                (
                    "fiber_number_absolute",
                    models.IntegerField(
                        help_text="The absolute fiber number that the fiber belongs to",
                        verbose_name="Fiber Number Absolute",
                    ),
                ),
                (
                    "fiber_number_in_bundle",
                    models.IntegerField(
                        help_text="The number of the fiber in the bundle that the fiber belongs to",
                        verbose_name="Fiber Number In Bundle",
                    ),
                ),
                (
                    "fiber_color",
                    models.TextField(
                        help_text="The color of the fiber that the fiber belongs to",
                        verbose_name="Fiber Color",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the fiber is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "layer",
                    models.TextField(
                        default="inner",
                        help_text="Inner or outer layer",
                        verbose_name="Layer",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "fiber_status",
                    models.ForeignKey(
                        blank=True,
                        db_column="fiber_status",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesfiberstatus",
                        verbose_name="Fiber Status",
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.flags",
                        verbose_name="Flag",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="project",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.projects",
                        verbose_name="Project",
                    ),
                ),
                (
                    "uuid_cable",
                    models.ForeignKey(
                        blank=True,
                        db_column="uuid_cable",
                        db_constraint=False,
                        help_text="The cable that the fiber belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.cable",
                        verbose_name="Cable",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fiber",
                "verbose_name_plural": "historical Fibers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFiberSplice",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "port_number",
                    models.PositiveIntegerField(
                        help_text="The port number on the component (e.g., 1-12 for a splice cassette)",
                        verbose_name="Port Number",
                    ),
                ),
                (
                    "merge_group_a",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID grouping ports on side A (IN) that share a fiber. Used for asymmetric components like splitters.",
                        null=True,
                        verbose_name="Merge Group A",
                    ),
                ),
                (
                    "merge_group_b",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID grouping ports on side B (OUT) that share a fiber. Used for asymmetric components like splitters.",
                        null=True,
                        verbose_name="Merge Group B",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cable_a",
                    models.ForeignKey(
                        blank=True,
                        db_column="cable_a",
                        db_constraint=False,
                        help_text="The cable of fiber A (denormalized for CASCADE delete)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.cable",
                        verbose_name="Cable A",
                    ),
                ),
                (
                    "cable_b",
                    models.ForeignKey(
                        blank=True,
                        db_column="cable_b",
                        db_constraint=False,
                        help_text="The cable of fiber B (denormalized for CASCADE delete)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.cable",
                        verbose_name="Cable B",
                    ),
                ),
                (
                    "fiber_a",
                    models.ForeignKey(
                        blank=True,
                        db_column="fiber_a",
                        db_constraint=False,
                        help_text="First fiber in this splice connection",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.fiber",
                        verbose_name="Fiber A",
                    ),
                ),
                (
                    "fiber_b",
                    models.ForeignKey(
                        blank=True,
                        db_column="fiber_b",
                        db_constraint=False,
                        help_text="Second fiber in this splice connection",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.fiber",
                        verbose_name="Fiber B",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node_structure",
                    models.ForeignKey(
                        blank=True,
                        db_column="node_structure",
                        db_constraint=False,
                        help_text="The component placement this splice belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.nodestructure",
                        verbose_name="Node Structure",
                    ),
                ),
                (
                    "shared_cable_a",
                    models.ForeignKey(
                        blank=True,
                        db_column="shared_cable_a",
                        db_constraint=False,
                        help_text="The cable of shared fiber A (denormalized for CASCADE delete).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.cable",
                        verbose_name="Shared Cable A",
                    ),
                ),
                (
                    "shared_cable_b",
                    models.ForeignKey(
                        blank=True,
                        db_column="shared_cable_b",
                        db_constraint=False,
                        help_text="The cable of shared fiber B (denormalized for CASCADE delete).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.cable",
                        verbose_name="Shared Cable B",
                    ),
                ),
                (
                    "shared_fiber_a",
                    models.ForeignKey(
                        blank=True,
                        db_column="shared_fiber_a",
                        db_constraint=False,
                        help_text="Shared fiber A for merged port groups (one fiber for all ports in group on side A).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.fiber",
                        verbose_name="Shared Fiber A",
                    ),
                ),
                (
                    "shared_fiber_b",
                    models.ForeignKey(
                        blank=True,
                        db_column="shared_fiber_b",
                        db_constraint=False,
                        help_text="Shared fiber B for merged port groups (one fiber for all ports in group on side B).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.fiber",
                        verbose_name="Shared Fiber B",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fiber Splice",
                "verbose_name_plural": "historical Fiber Splices",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFlags",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                ("flag", models.TextField(db_index=True, verbose_name="Flag")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Flag",
                "verbose_name_plural": "historical Flags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMicroduct",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("number", models.IntegerField(verbose_name="Number")),
                ("color", models.TextField(verbose_name="Color")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "microduct_status",
                    models.ForeignKey(
                        blank=True,
                        db_column="microduct_status",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesmicroductstatus",
                        verbose_name="Microduct Status",
                    ),
                ),
                (
                    "uuid_conduit",
                    models.ForeignKey(
                        blank=True,
                        db_column="uuid_conduit",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.conduit",
                        verbose_name="Conduit",
                    ),
                ),
                (
                    "uuid_node",
                    models.ForeignKey(
                        blank=True,
                        db_column="uuid_node",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.node",
                        verbose_name="Node",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Microduct",
                "verbose_name_plural": "historical Microducts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNode",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("name", models.TextField(verbose_name="Node Name")),
                (
                    "warranty",
                    models.DateField(blank=True, null=True, verbose_name="Warranty"),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=25832, verbose_name="Geometry"
                    ),
                ),
                (
                    "canvas_x",
                    models.FloatField(blank=True, null=True, verbose_name="Canvas X"),
                ),
                (
                    "canvas_y",
                    models.FloatField(blank=True, null=True, verbose_name="Canvas Y"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "constructor",
                    models.ForeignKey(
                        blank=True,
                        db_column="constructor",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Constructor",
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.flags",
                        verbose_name="Flag",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        db_column="manufacturer",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Manufacturer",
                    ),
                ),
                (
                    "network_level",
                    models.ForeignKey(
                        blank=True,
                        db_column="network_level",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesnetworklevel",
                        verbose_name="Network Level",
                    ),
                ),
                (
                    "node_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="node_type",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesnodetype",
                        verbose_name="Node Type",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Owner",
                    ),
                ),
                (
                    "parent_node",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_node",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.node",
                        verbose_name="Parent Node",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="project",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.projects",
                        verbose_name="Project",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_column="status",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesstatus",
                        verbose_name="Status",
                    ),
                ),
                (
                    "uuid_address",
                    models.ForeignKey(
                        blank=True,
                        db_column="uuid_address",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.address",
                        verbose_name="Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Node",
                "verbose_name_plural": "historical Nodes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProjects",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                ("project", models.TextField(db_index=True, verbose_name="Project")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Project",
                "verbose_name_plural": "historical Projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalResidentialUnit",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "id_residential_unit",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Residential Unit ID",
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(blank=True, null=True, verbose_name="Floor"),
                ),
                ("side", models.TextField(blank=True, null=True, verbose_name="Side")),
                (
                    "building_section",
                    models.TextField(
                        blank=True, null=True, verbose_name="Building Section"
                    ),
                ),
                (
                    "external_id_1",
                    models.TextField(
                        blank=True, null=True, verbose_name="External ID 1"
                    ),
                ),
                (
                    "external_id_2",
                    models.TextField(
                        blank=True, null=True, verbose_name="External ID 2"
                    ),
                ),
                (
                    "resident_name",
                    models.TextField(
                        blank=True, null=True, verbose_name="Resident Name"
                    ),
                ),
                (
                    "resident_recorded_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resident Recorded Date"
                    ),
                ),
                (
                    "ready_for_service",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ready for Service"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residential_unit_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="residential_unit_type",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesresidentialunittype",
                        verbose_name="Residential Unit Type",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_column="status",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesresidentialunitstatus",
                        verbose_name="Status",
                    ),
                ),
                (
                    "uuid_address",
                    models.ForeignKey(
                        blank=True,
                        db_column="uuid_address",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.address",
                        verbose_name="Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Residential Unit",
                "verbose_name_plural": "historical Residential Units",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTrench",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "id_trench",
                    models.CharField(max_length=10, verbose_name="Trench ID"),
                ),
                (
                    "construction_depth",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Construction Depth"
                    ),
                ),
                (
                    "construction_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Construction Details"
                    ),
                ),
                (
                    "internal_execution",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Internal Execution"
                    ),
                ),
                (
                    "funding_status",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Funding Status"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "house_connection",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="House Connection",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Length"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        spatial_index=False, srid=25832, verbose_name="Geometry"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "construction_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="construction_type",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesconstructiontype",
                        verbose_name="Construction Type",
                    ),
                ),
                (
                    "constructor",
                    models.ForeignKey(
                        blank=True,
                        db_column="constructor",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Constructor",
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag",
                        db_constraint=False,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.flags",
                        verbose_name="Flag",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributescompany",
                        verbose_name="Owner",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        db_column="phase",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesphase",
                        verbose_name="Phase",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="project",
                        db_constraint=False,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.projects",
                        verbose_name="Project",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_column="status",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributesstatus",
                        verbose_name="Status",
                    ),
                ),
                (
                    "surface",
                    models.ForeignKey(
                        blank=True,
                        db_column="surface",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.attributessurface",
                        verbose_name="Surface",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Trench",
                "verbose_name_plural": "historical Trenches",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWMSLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Layer Name")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Layer Title"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Enabled"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "min_zoom",
                    models.IntegerField(
                        default=8,
                        help_text="Minimum zoom level (0-22)",
                        verbose_name="Minimum Zoom",
                    ),
                ),
                (
                    "max_zoom",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum zoom level (0-22, blank = no limit)",
                        null=True,
                        verbose_name="Maximum Zoom",
                    ),
                ),
                (
                    "opacity",
                    models.FloatField(
                        default=1.0,
                        help_text="0.0 = transparent, 1.0 = opaque",
                        verbose_name="Opacity",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.wmssource",
                        verbose_name="WMS Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical WMS Layer",
                "verbose_name_plural": "historical WMS Layers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWMSSource",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("url", models.URLField(max_length=500, verbose_name="WMS URL")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Username"
                    ),
                ),
                (
                    "_password",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Password (encrypted)"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sort Order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated At"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.projects",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical WMS Source",
                "verbose_name_plural": "historical WMS Sources",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
