# Generated by Django 5.2.10 on 2026-03-10 16:01

from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    ModelPermission = apps.get_model('api', 'ModelPermission')
    RoutePermission = apps.get_model('api', 'RoutePermission')
    User = apps.get_model('auth', 'User')

    # Create groups
    admin_group, _ = Group.objects.get_or_create(name='Admin')
    editor_group, _ = Group.objects.get_or_create(name='Editor')
    viewer_group, _ = Group.objects.get_or_create(name='Viewer')

    # Model names that need permissions
    model_names = [
        'trench', 'conduit', 'microduct', 'node', 'address', 'cable', 'fiber',
        'fibersplice', 'container', 'area', 'residentialunit', 'featurefiles',
        'projects', 'flags', 'wmslayer', 'qgisproject', 'logentry',
        'trenchconduitconnection', 'trenchconduitcanvas', 'microductconnection',
        'microductcableconnection', 'nodestructure', 'nodeslotconfiguration',
        'cablelabel', 'containertype',
    ]

    # Create model permissions
    for model_name in model_names:
        # Admin: full access
        ModelPermission.objects.get_or_create(
            group=admin_group,
            model_name=model_name,
            defaults={'access_level': 'full'}
        )
        # Editor: edit access (except logentry)
        editor_level = 'none' if model_name == 'logentry' else 'edit'
        ModelPermission.objects.get_or_create(
            group=editor_group,
            model_name=model_name,
            defaults={'access_level': editor_level}
        )
        # Viewer: view access (except logentry)
        viewer_level = 'none' if model_name == 'logentry' else 'view'
        ModelPermission.objects.get_or_create(
            group=viewer_group,
            model_name=model_name,
            defaults={'access_level': viewer_level}
        )

    # Create route permissions
    # Admin: access to /admin/*
    RoutePermission.objects.get_or_create(
        group=admin_group,
        route_pattern='/admin/*',
        defaults={'allowed': True}
    )
    # Editor: no access to /admin/*
    RoutePermission.objects.get_or_create(
        group=editor_group,
        route_pattern='/admin/*',
        defaults={'allowed': False}
    )
    # Viewer: no access to /admin/*
    RoutePermission.objects.get_or_create(
        group=viewer_group,
        route_pattern='/admin/*',
        defaults={'allowed': False}
    )

    # Migrate existing users
    for user in User.objects.filter(is_superuser=False):
        if user.is_staff:
            user.groups.add(admin_group)
        else:
            user.groups.add(editor_group)


def reverse_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Admin', 'Editor', 'Viewer']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_add_permission_models'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions, reverse_migration),
    ]
