# Generated by Django 5.2.10 on 2026-03-28 14:08

import apps.api.models
import apps.api.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_add_wms_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='QGISProjectDataFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data_file', models.FileField(help_text='GIS data file (DXF, SHP, GeoJSON, GPKG, CSV, KML, GML)', storage=apps.api.storage.QGISDataFileStorage(), upload_to=apps.api.models.QGISProjectDataFile.get_data_file_upload_path, verbose_name='Data File')),
                ('original_filename', models.CharField(editable=False, help_text='Original filename, used for datasource path matching', max_length=255, verbose_name='Original Filename')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='api.qgisproject', verbose_name='QGIS Project')),
            ],
            options={
                'verbose_name': 'Data File',
                'verbose_name_plural': 'Data Files',
                'db_table': 'qgis_project_data_files',
                'unique_together': {('project', 'original_filename')},
            },
        ),
    ]
