# Generated by Django 5.2.10 on 2026-06-29 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_fix_microduct_node_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='id_address_2',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Address ID 2'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='id_address_2',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Address ID 2'),
        ),
        migrations.AlterField(
            model_name='qgisprojectdatafile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
