# Generated by Django 5.2.10 on 2026-07-01 19:21

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_add_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Type of Work',
                'verbose_name_plural': 'Types of Work',
                'db_table': 'type_of_work',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPipelineRecord',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('organisation', models.TextField(blank=True, null=True, verbose_name='Organisation')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('tel', models.TextField(blank=True, null=True, verbose_name='Telephone')),
                ('mobile', models.TextField(blank=True, null=True, verbose_name='Mobile')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modified At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_column='project', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.projects', verbose_name='Project')),
                ('type_of_work', models.ForeignKey(blank=True, db_column='type_of_work', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.typeofwork', verbose_name='Type of Work')),
            ],
            options={
                'verbose_name': 'historical Pipeline Record',
                'verbose_name_plural': 'historical Pipeline Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PipelineRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('organisation', models.TextField(blank=True, null=True, verbose_name='Organisation')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('tel', models.TextField(blank=True, null=True, verbose_name='Telephone')),
                ('mobile', models.TextField(blank=True, null=True, verbose_name='Mobile')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('project', models.ForeignKey(db_column='project', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_records', to='api.projects', verbose_name='Project')),
                ('type_of_work', models.ForeignKey(blank=True, db_column='type_of_work', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.typeofwork', verbose_name='Type of Work')),
            ],
            options={
                'verbose_name': 'Pipeline Record',
                'verbose_name_plural': 'Pipeline Records',
                'db_table': 'pipeline_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='idx_pipeline_record_project'), models.Index(fields=['type_of_work'], name='idx_pipeline_record_tow')],
            },
        ),
    ]
