# Generated by Django 5.2.10 on 2026-07-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_seed_pipeline_record_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestReason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Request Reason',
                'verbose_name_plural': 'Request Reasons',
                'db_table': 'request_reason',
            },
        ),
        migrations.AddField(
            model_name='historicalpipelinerecord',
            name='request_reason',
            field=models.ForeignKey(blank=True, db_column='request_reason', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.requestreason', verbose_name='Request Reason'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='request_reason',
            field=models.ForeignKey(blank=True, db_column='request_reason', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.requestreason', verbose_name='Request Reason'),
        ),
    ]
