# Generated by Django 5.2.10 on 2026-07-03 08:56

import django.contrib.gis.db.models.fields
import django.contrib.gis.db.models.functions
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_add_request_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPipelineInquiryArea',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=25832, verbose_name='Geometry')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modified At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pipeline_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.pipelinerecord', verbose_name='Pipeline Record')),
            ],
            options={
                'verbose_name': 'historical Pipeline Inquiry Area',
                'verbose_name_plural': 'historical Pipeline Inquiry Areas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PipelineInquiryArea',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=25832, verbose_name='Geometry')),
                ('geom_3857', models.GeneratedField(db_persist=True, expression=django.contrib.gis.db.models.functions.Transform('geom', 3857), output_field=django.contrib.gis.db.models.fields.PolygonField(srid=3857))),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('pipeline_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_areas', to='api.pipelinerecord', verbose_name='Pipeline Record')),
            ],
            options={
                'verbose_name': 'Pipeline Inquiry Area',
                'verbose_name_plural': 'Pipeline Inquiry Areas',
                'db_table': 'pipeline_inquiry_area',
                'ordering': ['created_at'],
            },
        ),
    ]
