# Generated by Django 5.2.10 on 2026-09-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0076_canvas_center_from_placed_nodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cable",
            name="funding_status",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Funding Status"
            ),
        ),
        migrations.AddField(
            model_name="conduit",
            name="funding_status",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Funding Status"
            ),
        ),
        migrations.AddField(
            model_name="historicalcable",
            name="funding_status",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Funding Status"
            ),
        ),
        migrations.AddField(
            model_name="historicalconduit",
            name="funding_status",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Funding Status"
            ),
        ),
        migrations.AddField(
            model_name="historicalnode",
            name="funding_status",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Funding Status"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="funding_status",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Funding Status"
            ),
        ),
    ]
